### ISSUE TITLE
Add support for NFC tags

### ISSUE THREAD

**Issue by Paethon** [iSoron/uhabits#101]
Are there any plans on adding support for NFC tags?

I.e. hold your phone to an NFC tag and a certain habit is automatically checked for Today without having to open the App first.

"Tap Log" for example supports something like this and I think it's a handy feature.

**Comment by iSoron** [comment]
I am not planning to add support to NFC tags directly, since that would require a considerably complex interface to manage these tags, and users would eventually start asking for other kinds of automation, such as QR code or location based checkmarks. What I am planning to do, instead, is to allow other apps, such as Tasker, to add checkmarks for you. See #6.

**Comment by Paethon** [comment]
Yes, thats probably the cleaner and more flexible solution

**Comment by Keavon** [comment]
I would really like this feature so that I cannot mark a task as complete at all unless I have an NFC tag present. That way I can't cheat, I have to go where the tag is located (near my habit/task).

**Comment by chennemann** [comment]
that would actually be not really feasible. what if you forgot to tap the tag or it's somehow not working. then you still want to be able to check it manually. 

the way I see this app is not as an app to keep you accountable but as a tool to help you track your stuff. 

of course it's hard to build a new habit but if you rely on a tool to force you to do it, it will probably not gonna work.
