### ISSUE TITLE
Fail to import the full backup

### ISSUE THREAD

**Issue by DelphineM** [iSoron/uhabits#1021]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
I have generated a full backup from my older phone. But when I'm trying to import it from my new phone, I have a fail message and no import.

## Steps to reproduce
1. Go to Settings in old phone
2. Click on Export full backup 
3. Save file in a cloud
4. Go to setting in new phone
5. Click on import
6. Choose file in the cloud
7. See error message

### NEW PHONE
 - Phone: OnePlus Nord
 - Phone Operating System: OxygenOS 11.1.1.3
 - App version: 2.0.2
### OLD PHONE
 - Phone: OnePlus 6T
 - Phone Operating System: OxygenOS 10.3.11
 - App version: 1.8.12

**Comment by marty-oehme** [comment]
I have just tried to export and import from the same App version: 2.0.2 and even that does not seem to work in my case.

Steps taken were:
1. Go to Settings on phone
2. Click on Export full backup
3. Save file in a cloud (nextcloud folder in my case)
3. Clear out the current trackers (batch delete from main screen)
4. Go to Settings on same phone
5. Click on import
6. Choose file in the cloud
7. See error message ('Failed to import data.')

Does it work for you if you do a test import/export from the same phone on version 2.0.2 @DelphineM ?

**Comment by diimdeep** [comment]
Confirming this bug. Lineageos 16

**Comment by DelphineM** [comment]
> Does it work for you if you do a test import/export from the same phone on version 2.0.2 @DelphineM ?

I just tried it and no (Export full backup / delete existing habits / import -> same error message)

**Comment by hiqua** [comment]
From your comments, there would be two issues:
* the issue from OP: some problem importing data across versions, and possibly even in the same version, for some data
* https://github.com/iSoron/uhabits/issues/1021#issuecomment-888558180 if there's no habit yet, impossible to import habits

@DelphineM:
* what's the error message? Screenshots could also be useful
* does your backup from 1.8 works if you import it back in 1.8?
* in your last comment, did you install 2.0.2 over 1.8.12? Does the app work fine otherwise?

If someone has a backup they'd be willing to share that reproduce the crashes mentioned, that could help.

I could not reproduce these issues with the following scenarios:
1:
* install 2.0.2
* export backup right away, after tutorial
* import

2:
* install 2.0.2
* add a habit
* tick one day
* export backup
* delete data
* import backup

3:
* export data from 1.8.*
* uninstall
* install 2.0.2
* import data

I think I've tried a few more, but basically no error.

If I had to venture a guess, I would bet on some frequencies in 1.8 not being compatible with 2.0.2. But I haven't checked.

**Comment by iSoron** [comment]
Thank you for the bug reports, @DelphineM, @marty-oehme and @diimdeep. As @hiqua mentioned, having error log would be useful. Could you please try to import the data, then immediately generate a bug report (in Settings / Generate bug report) after it fails? If you are willing to share your backup files with us, so that we can easily reproduce this bug, please feel free to send them to dev@loophabits.org. We won't share them publicly.

@hiqua We haven't changed frequencies internally; they are still stored in exactly the same way.

**Comment by DelphineM** [comment]
Thanks everyone.

@diimdeep 

"workaround is to create at least 1 habit and then import from backup"
-> Thanks but it didn't worked for me

@hiqua 

- "does your backup from 1.8 works if you import it back in 1.8?" 
-> no, same error message (in french) : "Import des données échoué"
- "in your last comment, did you install 2.0.2 over 1.8.12? Does the app work fine otherwise?" 
-> no, it's a new phone, only the 2.0.2 version has been installed. Yes, the app seems to work perfectly.

@iSoron I just sent by email:

- the bug report
- the backup file
- some screenshots

**Comment by hiqua** [comment]
If you export it again do you get the same file? If not, does it have the same file size at least? Does it work better?

We can't exclude a simple file corruption I guess.

**Comment by DelphineM** [comment]
I tried at different times, on different days and so I have several backup files with different names (date). At least one of them should be different because I added a check mark on a habit.
They are all the same size.

**Comment by iSoron** [comment]
Hi @DelphineM, thank you for the bug reports and for the files. Unfortunately, I am still unable to replicate this issue. In my tests, Loop is able to import your backup file without any problems. I ran the tests on a OnePlus 8T phone, running Oxygen OS 11.0.5.6 and Loop 2.0.2 (release build). The bug report you sent us also does not show any error messages related to importing.

You mentioned that you are trying to import the file directly from the cloud. Does the problem happen if you first download the file to your phone, then import it from the Downloads folder?

**Comment by hiqua** [comment]
And if you don't mind sharing, which cloud service do you use, and more specifically which cloud client (if there are several) to access your files?

**Comment by iSoron** [comment]
Closing for lack of response.

**Comment by hiqua** [comment]
Interesting, then we should be able to reproduce this. I guess there are several clients, which one do you use exactly?

**Comment by hiqua** [comment]
Ok, maybe it would make sense to close here and report it to nextcloud then, could you do it @t26y? They might have more bandwidth to reproduce the issue.

**Comment by hiqua** [comment]
l
