### ISSUE TITLE
Allow app to sync data across devices

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#104]
It would be nice if Loop could synchronize your habit data across multiple devices. This feature has been one of the most frequently requested so far. It also opens many interesting possibilites, such as syncing data with a future desktop or web client.

Since this feature raises many privacy and security concerns, here is my non-comprehensive list of requirements:
1. It should be completely opt-in, and the app should still be fully functional with this feature disabled.
2. If there is software running on a server to make this feature work, this software should be fullly open-source and self-hostable.
3. It goes without saying, but the whole thing should just work. In particular, it must gracefully handle the case where multiple devices make changes while offline, then go online. The solution must be able to merge the offline changes, not simply discard all the changes made all clients, except one.

Because of requirement 2, most commonly used solutions such as Parse, Firebase or Play Games Services are out of the picture. Requirement 3 probably eliminates file-based sync solutions, such as Syncthing, Google Drive or Dropbox.

**Comment by iSoron** [comment]
I am currently experimenting with custom back-end solution, implemented in node.js, on the branch `feature/sync`, but it's not usable yet.  I will post here once it works somewhat properly.

**Comment by NiklasMM** [comment]
Do you want to host that backend yourself and make it available to all users? Or would that be a self-hosted solution, which everyone could set-up for themselves?

**Comment by iSoron** [comment]
Hi @NiklasMM, I will probably host an instance myself and make it available for all users. I might start accepting donations to keep the server running. In any case, you will also be able to run a private instance of the server yourself.

**Comment by PunctualEmoticon** [comment]
Would it be possible to use git for this? Have each device make its own little repo with the data in it, and then either have each sync with a server, or possibly sync directly with each other (decentralized).

For merging, only conflicts for the same habit and day would be an issue.  I think choosing the most recent change would be a fine solution.

**Comment by iSoron** [comment]
@PunctualEmoticon If you are suggesting to create a local git repository on each phone with the database file, then I think we would run into the same problems as using Syncthing or Dropbox; namely, there is not enough granularity for git to merge things automatically. Only if we split the database into multiple files, would git (or Syncthing/Dropbox) be able to help us, but this doesn't strike me as a very good solution.

**Comment by PunctualEmoticon** [comment]
Yes, that's what I was suggesting.
But unlike those file syncing services, git isn't limited to just checking files as a whole.  It looks at the contents of the files (if they're ultimately text files), and can resolve changes automatically, unless the same line has been modified on both branches since the branches last split.
Source: http://www.drdobbs.com/tools/three-way-merging-a-look-under-the-hood/240164902

**Comment by xdmx** [comment]
You may consider the ability to sync it with a nextcloud/owncloud server, that'd be nice

**Comment by fwuensche** [comment]
I believe you don't want to have any server structure on your side. So, as you suggested above, maybe we could try to use Dropbox. 

Take a look at 1password for example. It works like a charm across my devices (mobile and laptop) and it's always in sync by using Dropbox as "database". Do you believe that might be feasible?

**Comment by kyriakosbrastianos** [comment]
What about webdav? I would like to share and use data with apps like nextcloud tasks & calendar and qownnotes: https://github.com/pbek/QOwnNotes 
QOwnNotes is great on desktop and syncs great with nextcloud tasks so u get web interface too and loop habits is amazing on android. A collaboration will be great with these services/apps.

**Comment by omarbenhamid** [comment]
What about using cloudant, it is à cloud service based on opensource couchdb technology ? 
We could use https://github.com/cloudant/sync-android library. It should transparent fit thé 3 d'équipements ?

**Comment by MaluNoPeleke** [comment]
An optional Play Games Services support would be nice, even if it doesn't meet all requirements.

**Comment by recheej** [comment]
What about a web based solution? Send data back and forth between the web server. The web server stores the information in a database.

**Comment by mr-flibble** [comment]
Hello, just an idea: 
Since now application uses sqlite, would it not be too time-consuming to allow a user to attach an application to their own mysql postgresql server? The application would be in the online only mode but would be available from multiple devices.

**Comment by jharder01** [comment]
I'm in favor of self hosted options as they are in-line with the spirit of this project. Granted, a shared, public sync server may help instead awareness of the app. 

Additionally, I would love to be able to sync my Android Loop data locally to a personal Grafana/InfluxDB server for data logging and visualization.

**Comment by namdnguyen** [comment]
Where is the application sqlite database, not backup files, stored on Android? I'm having trouble finding it.

**Comment by eppeters** [comment]
I have the same question as namdnguyen

**Comment by jbrinker** [comment]
What about sync'ing up with third party services such as Gmail's Tasks or Drive. This way you would not have to worry about hosting back-end service endpoints for data sync'ing and storage.  You would also not have to burden yourself with the cost of hosting.

**Comment by trymeouteh** [comment]
This would be cool. The best way to do this is to not use a server but link each device together in a P2P way. Kinda like SyncThing.

Also it will need to encrypt the data on transit to prevent any tampering or having it being intercepted in transit.

**Comment by bendespain** [comment]
Why not use Google drive like this says: https://stackoverflow.com/questions/30233198/how-to-save-app-data-on-google-drive
with this direction: https://developers.google.com/drive/android/appfolder
and this: https://developers.google.com/drive/android/files#writing_files

If this creates conflicts then just make the app (if cloud-enabled is setup/chosen) wait until the drive connection is up, before it is allowed to write. Then Google drive is responsible for any conflicts, right?

**Comment by bendespain** [comment]
Or maybe just syncing it to Google Calendar?

**Comment by trymeouteh** [comment]
Google Drive would not be good for privacy. It would be best to have the two devices talk to eachother.

**Comment by CryptoStar2000** [comment]
Awesome! I would appreciate this!!

**Comment by madl-ash** [comment]
Any update on this @iSoron ?
also, i cant find `features/sync` branch.is it deleted?

**Comment by LoopTrooper** [comment]
Still have huge interest in this feature :-)!!

**Comment by CryptoStar2000** [comment]
Is the app still in development? Sync would be so great. Or at least the ability to save and restore in cloud.

**Comment by trymeouteh** [comment]
I have a suggestion on how to make the sync feature easy to implement.

Have it so the habits is saved as a file on your android device. Every time you add/remove a checkbox, add or remove a habit it will update the file and save it. All that is needed now is for the user to setup Syncthing or their cloud storage app to sync the data between their devices. This method will not require adding a syncing feature to Habits and allows the users to control their data by letting them choose what services to sync their data with. A good app for cloud storage syncing is FolderSync and there are other apps like FolderSync out there.

By going down this method you will also be for filling the automatic backup feature request too.

**Comment by hiqua** [comment]
@iSoron can you expand on what should be synchronized, to understand better why Syncthing (in particular) is not an option? I have this in mind:

* name of the habit
* frequency
* reminder
* archived status
* days on which it has been completed
* color

Let me know if I'm forgetting something.

Now, for an habit, you could have a corresponding folder (folder name is a UUID which does not change), containing two subfolders
* `journal`: contains an empty file like `2019_07_11` for every day the habit has been completed.
* `settings`: contains `name`, `frequency`, `reminder` and `color` with a timestamp appended to these names, containing the corresponding parameters. The app would only take the last one into account (and possibly remove the old ones, or keep them as a backup to revert changes).

The entries in `journal` would not create real conflicts (e.g., if you tick on two devices then untick on one device then sync, then (with syncthing) the habit would end up being ticked). You could also use the same kind of timestamp system if need be, but I don't think it's necessary. For `settings`, no file conflict either, but the last option will be kept.

If you create two habits with the same name on different devices, they won't be merged, they will be separate habits, which I think is fine.

The main problem is that the current format is sqlite (AFAIK), so that would be a change there. I assume there's some performance penalty. To me, having a simple structure for which I don't need yet another tool to synchronize my data between devices would be a big win. I also don't think the performance penalty is that huge.

I'd be happy to learn about shortcomings of this approach. Again, the benefits is being able to synchronize data just by:
* changing the current data format
* using a synchronization tools like the ones you've mentioned in your first post

**Comment by iSoron** [comment]
@hiqua That's an interesting solution. Please feel free to code a prototype, but I'm guessing that you will run into several issues:
1. This requires users to install and maintain an external piece of software to make the feature work. I expect most users will find this too complicated, and simply never use the feature. I'm fine with features for power users (e.g. Tasker support) but I feel this one should be accessible to everyone.
2. This implementation would require Loop to store the database in a public folder. Besides the security and privacy implications of this decision, it should also be noted that Android in general is [moving away from such practice](https://developer.android.com/preview/privacy/scoped-storage). It's not clear if this solution would still work after Android Q.
3. Loop would need to monitor the filesystem for external changes and update the JVM objects accordingly. If the filesystem and JVM objects ever get out of sync, the app could crash trying to write into non-existing folders, or something similar. This also opens up the door to all kinds of race conditions. What happens if the folder is deleted externally between the time we check its existence and the time we read its contents?
4. This solution is incompatible with future web clients.

**Comment by hiqua** [comment]
Thans for taking the time to review my comment. I'll try to clarify possible solutions point by point:

1. This does not have to exclude any other in-app synchronization feature. My main point was that, by changing the data format (from sqlite), you could make it friendlier to dumb file synchronization apps, which would partially resolve this issue for some users who already use such apps. An in-app synchronization feature could still be implemented (almost) independently.
An example of an app that gives people the choice as to how synchronization is done is simpletask: https://github.com/mpcjanssen/simpletask-android. It might look complicated with their multiple build systems, but this doesn't have to be this way. There might be other advantages of sqlite that I'm not aware of though.

2. I think it's fair to keep the files in Loop's private folder, and leave it to synchronization apps and their users as to how they want to synchronize this data. Also note that, as of now, apps like WhatsApp (which arguably has more private content than Loop) still store a lot of their data in the common (public) storage. Once (if) public folders are deprecated, I'm confident workarounds will come up to still have some kind of public folders, or at least to share these folders via synchronization apps.

3. I have been trying to find such conflicts, but I haven't found real ones yet. To "delete" a habit a `deleted` file can be added into the folder, instead of actually deleting any file or folder in the file system. If somebody manually deletes a folder, then all bets are off of course (but it's the same if somebody opens the sqlite database manually and injects some weird data in it).
Files and folders don't have to be monitored if the user is fine only having eventual consistency (e.g., by rescanning the files every 24h). To always have consistent data across devices, there's indeed some monitoring required, be it of files with or with a connection to a server with the solution you currently have in mind. I'm not sure if one is clearly better than the other (I'm assuming the inotify API is available on Android, but I don't really know).

4. I admit I am not aware of the requirements of future web clients.

**Comment by MoSattler** [comment]
Hi @hiqua, did you make any progress on this?

**Comment by hiqua** [comment]
@MoSattler no.

**Comment by mdaudali** [comment]
Hey! Just thought I'd add my 2 pence here - from a theoretical point of view, Conflict Free Replicated Data types would be the way to go (https://crdt.tech/ for some background reading). These data structures allow each node / device to operate over the data with defined operations (e.g, marking the task as completed), and have defined serialisation rules that ensure multiple nodes can merge their operations together, resulting in a consistent end view. 

From a practical perspective, this can be implemented in a couple of different ways. My undergrad dissertation (feel free to ask for a copy) used an OCaml library called Irmin that actually interfaces with Git, but manages the underlying merge semantics for you. An example structure for this project could be a simple JSON structure for each habit, with intervals marking the dates that have been marked complete. The 3 way merge would simply merge these intervals, always favouring completed over uncomplete. Devices would simply `git push` to a server, letting the server handle the merge.

This would satisfy your second and third requirements - For example, it would likely be under 100 lines of OCaml and easily made open source. By definition, it would handle multiple devices syncing at any point in time, even with potentially conflicting changes. It'd also make it really easy to backup, since backing up is simply git clone.

If I've not explained myself well, do feel free to ask for clarification! It's actually quite simple to implement, but may require a change in how the data is stored. I may try and give it a go over the next few months if I get time.

**Comment by tobiasgrosser** [comment]
> Hey! Just thought I'd add my 2 pence here - from a theoretical point of view, Conflict Free Replicated Data types would be the way to go (https://crdt.tech/ for some background reading). These data structures allow each node / device to operate over the data with defined operations (e.g, marking the task as completed), and have defined serialisation rules that ensure multiple nodes can merge their operations together, resulting in a consistent end view.
> 
> From a practical perspective, this can be implemented in a couple of different ways. My undergrad dissertation (feel free to ask for a copy) used an OCaml library called Irmin that actually interfaces with Git, but manages the underlying merge semantics for you. An example structure for this project could be a simple JSON structure for each habit, with intervals marking the dates that have been marked complete. The 3 way merge would simply merge these intervals, always favouring completed over uncomplete. Devices would simply `git push` to a server, letting the server handle the merge.
> 
> This would satisfy your second and third requirements - For example, it would likely be under 100 lines of OCaml and easily made open source. By definition, it would handle multiple devices syncing at any point in time, even with potentially conflicting changes. It'd also make it really easy to backup, since backing up is simply git clone.
> 
> If I've not explained myself well, do feel free to ask for clarification! It's actually quite simple to implement, but may require a change in how the data is stored. I may try and give it a go over the next few months if I get time.

This overall sounds quite interesting, but I would assume that OCAML cannot be really shipped easily to Android. I wonder if this could be done without android?

**Comment by mdaudali** [comment]
The OCaml would only be needed on the server side - the communication protocol is Git or even a REST API and so is language agnostic, so the app can use whatever is currently in use. 

OCaml also isn't necessary for the server side - I mention it as it's what I used for my project and there's already a well tested library (https://irmin.org/) for CRDTs. However, it can be implemented in any language - it'd just take a bit more work to implement.

**Comment by tobiasgrosser** [comment]
Nice, this sounds great for my perspective. I am not the project lead, but from experience, I feel that some proof of concept code typically helps to kick things off. I would be super interested to see this feature.

**Comment by falcorr** [comment]
I'd be happy even with simply having an option to sync with Google Drive, Dropbox, whatever.

**Comment by AliDjango** [comment]
nextcloud/owncloud/webdav support is also good.

**Comment by ramzan** [comment]
What about [Etebase](https://www.etebase.com/)? It's the backend used in [Etesync](https://www.etesync.com/).

**Comment by iSoron** [comment]
@ramzan Thank you for the link. That actually looks quite promising. We should look into it.

**Comment by iSoron** [comment]
A partial implementation of this feature has been merged into the `dev` branch and will probably be available in Loop 2.0, unless we find serious bugs or limitations in our implementation.

If you would like to try it out an early work-in-progress version of this feature and give us some feedback, it is also available in [v2.0.0-alpha](https://github.com/iSoron/uhabits/releases/). Please note that alpha releases may contain serious bugs that can cause you to lose your entire data. You should create a full database backup before trying it out.

**Comment by lkraav** [comment]
> A partial implementation of this feature has been merged into the dev branch and will probably be available in Loop 2.0, unless we find serious bugs or limitations in our implementation.

Tyvm :pray: Is there a short summary of how it technically works, somewhere, or gotta dig through code?
