### ISSUE TITLE
make HabitHistoryView a library

### ISSUE THREAD

**Issue by goog** [iSoron/uhabits#108]
i like the HabitHistoryView very much and want to apply it to my class project , but iam new to android , is there an easy way or tutorial to learn it ?  thx a lot!

**Comment by iSoron** [comment]
It should not be very hard to reuse the `HabitHistoryView` class in another project. The only reference to project-specific classes is in the function `refreshData`. I will not make it into a library, however, because I would not have time to maintain it. The source code is GPL, though, so feel free to do that if you would like. Also, feel free to ask me any specific questions about the class.
