### ISSUE TITLE
App Clone

### ISSUE THREAD

**Issue by tonya1545b** [iSoron/uhabits#1127]
I think this app is a app clone

https://play.google.com/store/apps/details?id=com.herman.habits

**Comment by hiqua** [comment]
It's fine to clone the app, although cloning it just for the sake of it is rather, well, counter-productive from a user's perspective.

They might be in violation of the license though, given that their latest update is more recent than the last commit on their fork: https://github.com/hedongfu/7-Habits

**Comment by iSoron** [comment]
Thank you for letting us know, @tonya1545b. As @hiqua mentioned, clones are allowed, as long as the developers follow the terms of our license. I am removing the links to the cloned app, however, because we do not endorse them, and because I want to avoid spammers from promoting their own apps in our bug tracker.
