### ISSUE TITLE
AMOLED mode isn't realized if already in night mode 

### ISSUE THREAD

**Issue by disser** [iSoron/uhabits#118]
In order to get true blacks, night mode must be turned off and back on again.

**Comment by iSoron** [comment]
Thank you for reporting this bug. If you exit the settings using the back button, it does not update, but if you exit using the up navigation arrow, it works correctly.

**Comment by AnirudhaAgashe** [comment]
The color is changed when user uses Up button because onCreate gets called : [(reference).](http://stackoverflow.com/questions/19216410/oncreate-being-called-on-activity-a-in-up-navigation)  
This is because the code for onSupportNavigateUp doesn't simply finish the current activity, it does more than that.
onSupportNavigateUp() method source code which gets called when up button is clicked : [(code).](https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/app/AppCompatActivity.java)  

One way to solve this would be to  override onBackPressed and call onSupportNavigateUp() which will make the flow consistent

**Comment by iSoron** [comment]
@AnirudhaAgashe Yes, that would be fine as a temporary solution. I think a more proper solution would be, after the activity is resumed, we check if the theme preference has changed while the activity was paused, and if so we restart the activity by calling [refreshTheme()][1].

[1]: https://github.com/iSoron/uhabits/blob/aa41717c666ebc9711b796575ff95a00161d1218/app/src/main/java/org/isoron/uhabits/MainActivity.java#L197
