### ISSUE TITLE
Rename launcher icon to "Loop"

### ISSUE THREAD

**Issue by rawkode** [iSoron/uhabits#119]
So many apps opt to change the name of the app on the launcher and I hope I'm not the only one that finds it infuriating. You're making it difficult to launch the app after install by making people think.

I'd like to see this resolved 👍

**Comment by iSoron** [comment]
I am considering this, but changing it now would force all existing users to wonder where did the app go in the app drawer, or if it got uninstalled. Also, for the the majority of new users, they probably have Google Play configured to add the app to the home screen, in any case, since this is the default.

**Comment by LuccoJ** [comment]
I kinda like app icons having descriptive labels, especially when I'm installing them for other people. My mother doesn't really understand what "Loop" is supposed to mean here, but she sure understands "Habits", especially given it's translated to her native language in the launcher.
