### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#13]
Dark theme for bright days.

**Comment by iSoron** [comment]
Thank you for the suggestion.

**Comment by alexholoo** [comment]
Or maybe let users customizing the background by themselves. Introduce a
bit more flexibility in the future.

**Comment by iSoron** [comment]
I am currently implementing this feature on the branch `feature/dark-theme`. Here are some screenshots of the main screen and settings. The statistics screen still needs some work. Feedback is very welcome.

![night-mode-1](https://cloud.githubusercontent.com/assets/4699657/14411214/b616c108-ff0f-11e5-9875-f302f2707539.png)
![night-mode-2](https://cloud.githubusercontent.com/assets/4699657/14411218/c845f92a-ff0f-11e5-8533-626777eb54ee.png)
![night-mode-3](https://cloud.githubusercontent.com/assets/4699657/14411219/cbd4d96c-ff0f-11e5-9122-1b5576a8c948.png)

**Comment by sojusnik** [comment]
From an energy saving point of view, especially for AMOLED displays, the dark version should mainly consist of real black color with some grayish elements. But I also can imagine, that this will be hard to implement, since your UI relies on several gray tones, to look somehow appealing. Nevertheless, I'm eager to test the new dark version out and give some feedback (already subscribed to the beta channel on the play store).

**Comment by iSoron** [comment]
This feature has now been merged into `dev`. There is also an AMOLED dark theme, which you can activate in the settings screen. I'm closing this issue, but feel free to post any feedback, either here or in a new issue.
