### ISSUE TITLE
Allow moving multiple habits as a group

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#137]
Despite several habits being selected, only one of them is dragged.

**Comment by iSoron** [comment]
Thank you for the suggestion. I would expect this to be surprisingly hard to code, though. What happens when there are gaps between the selected habits? What happens when some of the habits are not visible on the screen, etc? For this reason, I am not planning on implementing it myself, but pull requests are very welcome.

**Comment by klanmiko** [comment]
I can help implement this if it is still open, make it so that the gaps are filled by the next element in the list when multiple habits are moved.

**Comment by iSoron** [comment]
Sure, you can give it a shot. Please, let me know if you have any questions implementing this.

**Comment by iSoron** [comment]
Given how hard it is to implement this feature and how infrequently users move habits in the first place, I no longer think this feature should be implemented.
