### ISSUE TITLE
Importing backup not working

### ISSUE THREAD

**Issue by itzluxman** [iSoron/uhabits#140]
I exported both csv and full Db to a folder in my sd card but its showing blank pop up when importing. 

Is this an issue or a rare exception in my device (Karbonn android one 6.0)

**Comment by iSoron** [comment]
Could you send me a bug report from within the app? (Settings / Generate bug report). Immediately after you export, does the app ask you which app would you like to share the file with? Can you see the files when you connect your phone to your computer?

**Comment by iSoron** [comment]
Please let me know if this is still an issue.

**Comment by edio** [comment]
Same for me.

Exported backup with Loop from Google Play. Saved to sdcard/Downloads

Uninstalled Loop. Installed Loop from F-Droid (it has newer version there, but different signature, thus android requires to uninstall previous version).

Tried to import, but got empty popup instead of file selection dialog.

Xperia X Compact, Android 7.0

**Comment by licaon-kter** [comment]
You've given Permission->Storage for the app, right?

**Comment by edio** [comment]
Ok, got it. I had to copy backup file to org.isoron.uhabits, but that's very unobvious. I do understand, that that, perhaps, is required to keep app permissions at minimum.

A possible solution would be to check the directory with backups, and if there're no files, show a message, that user must ensure, that backup is placed into this directory.

**Comment by edio** [comment]
App didn't requested those.
Maybe something is wrong with the version distributed via F-Droid. But it only requires 
* control vibration
* run at startup

http://imgur.com/ElaN7xj

**Comment by licaon-kter** [comment]
Not sure they're implemented though, since Android 6 requires extra coding to handle that.

**Comment by iSoron** [comment]
Starting in version 1.7, we will have a new import dialog, which will be able to import files directly from the Downloads folder, or from cloud services, such as Google Drive. You will not need to copy the file manually into that folder anymore. This will hopefully make things more intuitive. As @licaon-kter says, this is related to #112.

The app does not require any dangerous permissions, such as reading the entire SD card. This is intentional, and will not change any time soon.
