### ISSUE TITLE
What algorithm does it use?

### ISSUE THREAD

**Issue by moshpirit** [iSoron/uhabits#142]
The app itself is great and I love it. A day is not complete if I didn't check my habits, but I miss a bit of information in the Readme.md file explaining how does it really work. I mean, AFAIK after 21 days of continuous work, it creates a habit, but I don't see that in the app, and what happens when it's once per week? After how many time it's a habit created? That kind of explanation is what I'm missing here. Thanks a lot for doing that, the app is so cool!!

**Comment by iSoron** [comment]
Hey, I'm glad you like the app. This issue is the same as #52, but I will explain it here.

For daily habits, the formula works like this. Each day receives a value, which is either 100% if you have performed the habit on that day, or 0% if you haven't. To compute the score for a given day, let's say today, we take a weighted average of the values for each day in the past, from the very first day you started your habit, until today. The weight decays exponentially over time, so recent repetitions have more importance. This kind of average is called [exponentional smoothing][1]. The precise parameters on the formula were tweaked so that, if you perform a new daily habit perfectly, the score reaches 80% after one month, 96% after two months and 99% after three months.

For non-daily habits, the idea is the same, but the parameters were adjusted so that it would take longer to reach the same percentages. If your habit is repeated every other day, then it takes two months to reach 80%, and if you habit is weekly, then it takes seven months, and so on.

This formula has many nice properties. For example:
* Every repetition counts, even way back in the past. This is not true for other simpler formulas, such as counting how many times have you performed the habit in the last week/month/year and then dividing by the number of days in that interval.
* If you have a poor score, then a few repetitions can bring your score up quite quickly. As you get better, however, the reward for each repetition gets smaller and smaller, so you have to keep at it if you want to see any increase.
* If you have a high score for a very long time and you take a short break, it's quite easy to restore your score back to what it was. If you start taking frequent breaks, however, then your score will suffer.

If you are interested in the source code, the formula is implemented in the file [Score.java][2].

I should write about this in the FAQ. Thanks for reminding me.

[1]: https://www.otexts.org/fpp/7/1
[2]: https://github.com/iSoron/uhabits/blob/94a48133ec9328cd09d4afd1c4a836c3935c2f83/app/src/main/java/org/isoron/uhabits/models/Score.java#L51-L81

**Comment by aleksejrs** [comment]
> we take a weighted average of the values for each day in the past, from the very first day you started your habit, until today.

So I guess it was a bad idea to take an old log out and enter the data from it while ignoring the unknowns that came after it.

**Comment by vinay-x** [comment]
Thanks a lot for writing this.

**Comment by iSoron** [comment]
This is now included in the [FAQ][1].

[1]: http://loophabits.org/faq.html#q10
