### ISSUE TITLE
Receive shared data from other app, etc. Runtastic

### ISSUE THREAD

**Issue by perqin** [iSoron/uhabits#146]
I think it would be a useful feature. For example I create a habit of running every week and I use Runtastic or any other app to record my exercise. After finishing, it will ask me to share(something like "I am using Runtastic and I've accomplished today's exercise!!"). Then I could share it to Loop Habit Tracker and it checks the corresponding habit for me.
How do you think this idea? I am a newbie to Android development but I think it won't be hard to implement it.

**Comment by iSoron** [comment]
Thank you for the suggestion. I am not sure if the data shared by other apps would contain enough information for us to figure out what habit are they referring to. When Runtastic shares something with other apps, for example, what exactly does it send? Is it just a string?

**Comment by perqin** [comment]
@iSoron I test it and it is just a string. Runtastic also support custom sharing text but I think it makes things more complex. Maybe a better approach is parsing keyword from the shared string. App name that shares the string might also help.

**Comment by iSoron** [comment]
Hi @perqin, I would like to avoid parsing strings, since they are bound to break in future updates. On the bright side, I have recently implemented integration with Tasker (and other automation apps, such as Llama) so this can be easily done using something like [Autoshare][1]. Please, [see the wiki][2] for more info.

[1]: joaoapps.com/autoshare/
[2]: https://github.com/iSoron/uhabits/wiki/Integration-with-Tasker

**Comment by perqin** [comment]
@iSoron Hmm using Tasker is a great idea! Looking forward to its release:)
