### ISSUE TITLE
suggestion: add habit behavior (positive, negative)

### ISSUE THREAD

**Issue by Elemerald** [iSoron/uhabits#15]
A feature where you can add positive or negative habits. You also can filter/group your habits. Negative habits maybe get an achievment for not doing this habit for X days.. 

example: achievment for not "smoking" since may (habit of user), or for 3 days etc.

**Comment by iSoron** [comment]
Thank you for the suggestion. After considering this a while ago, I have decided not to implement this feature. If you have a negative habit you want to stop, it is probably a better idea to rephrase it in a positive way. Using your example, instead of having the bad habit "Did you smoke today?" you could have the good habit "Did you have a smoke-free day today?". Another example, instead of "Did you eat junk food today?" you could have "Did you eat healthy today?". In this way, every time you open the app to put a checkmark, you are rewarding yourself for some good behaviour, instead of getting punished.

Please, feel free to try to change my view.

**Comment by c33s** [comment]
@iSoron any chance to get this feature? i tried to change your view with https://github.com/iSoron/uhabits/issues/351#issuecomment-355340227
i would donate for such a feature.

**Comment by herrbrixter** [comment]
> Thank you for the suggestion. After considering this a while ago, I have decided not to implement this feature. If you have a negative habit you want to stop, it is probably a better idea to rephrase it in a positive way. Using your example, instead of having the bad habit "Did you smoke today?" you could have the good habit "Did you have a smoke-free day today?". Another example, instead of "Did you eat junk food today?" you could have "Did you eat healthy today?". In this way, every time you open the app to put a checkmark, you are rewarding yourself for some good behaviour, instead of getting punished.
> 
> Please, feel free to try to change my view.

@iSoron This is tedious for negative habits. Negative habits are meant to be done less frequently. You shouldn't be updating the tracker daily if you aren't doing the bad habit (ex. not smoking).

Positive habit (ex: go to the gym daily)
Habit Action: going to the gym
Tracking: you add a Yes in the habit tracker daily.

Negative habit (ex: don't smoke)
Habit Action: the act of smoking
Tracking: You add a Yes if you smoked. It is only meant to be updated on the days you smoked.

If you smoked only 1 out of 30 days, it is harder for the user to update the tracker for 29 days for not doing an action consciously. The intentional action is smoking. I don't see the point of tracking the habit for 29 days for taking no action.

Another reason, negative habits is subject to change until the end of day. If you said at 11:00PM that you had a smoke free day but decided to smoke anyway at 11:25PM, then the user has to update the tracker twice. If you only track the action (smoking), you only update the habit tracker once.
