### ISSUE TITLE
import doesn't doesn't work, see #1598

### ISSUE THREAD

**Issue by SimonDedman** [iSoron/uhabits#1705]
Per #1598 which isn't reopened by my comment

**Comment by hiqua** [comment]
Please edit your bug to follow this template: https://github.com/iSoron/uhabits/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md

It's hard for us to reproduce the bug otherwise, hard enough that it'd make sense to just close this again. Thanks!

**Comment by SimonDedman** [comment]
Pre-submission checklist

    I am submitting a bug report, not a feature request.
    I have searched for similar issues, but did not find any matches.

Description

A clear and concise description of what the problem is.
- Import doesn't work. Error = "file not recognized"
Steps to reproduce
- Make a full export. In another app, phone, the import generates error: "file not recognized"

System information

    Phone: exported on Asus Zenfone 6, importing on Samsung Galaxy Note 9. Original poster likely using a different combination for the same result.
    Phone Operating System: Exported on Android 11 I believe. Current version on the note is 10.
    App version: 2.1.1

**Comment by hiqua** [comment]
How do you export the backup exactly?

**Comment by SimonDedman** [comment]
Settings, export full backup

**Comment by hiqua** [comment]
That opens a "share" menu, doesn't it? Which app do you then select?

**Comment by officer-k22** [comment]
I also have import problems, which might be due to different reasons than SimonDedman's.

Pre-submission checklist

    I am submitting a bug report, not a feature request.
    I have searched for similar issues, but did not find any matches.

Description

>Settings
>Import Data
>File Browser opens
>I click my backup file (.db)
>the app vanishes/closes/minimizes itself
>sometimes it says "App terminated repeatedly"

I have created the backup file via "export complete backup" before installing a new LineageOS version after a factory reset. 
I have translated the messages and setting names from German, so excuse me if they are actually different in the english original.

System information

    Phone: Fiarphone 3+
    Phone Operating System: Android 13, LineageOS 20-20230501-NIGHTLY-FP3
    App version: 2.1.1 from F-Droid

**Comment by iSoron** [comment]
@hiqua Thanks for helping debug this issue.

@SimonDedman Import errors are usually caused by one of the two issues:
1. The file was exported in a new version of Loop (e.g. v2.1) and is being imported in an old version (e.g. v2.0); or
2. The exported file is not a full backup, but a CSV export of your data. You can rule this out by checking the file extension. If it's a zip file, then it's not a full backup, and Loop won't be able to import it.

If you think neither issue apply in your case, would you mind send me the backup file at dev@loophabits.org so that I can try to reproduce the issue? Otherwise, there is not enough information in this bug report for us to take any action.

@officer-k22 Please open a separate bug report.

**Comment by SimonDedman** [comment]
Seems I exported CSV not db so that's that, sadly.
