### ISSUE TITLE
Persist notifications across reboots and upgrades

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#172]
By default, when the phone is rebooted or when the application is destroyed for any reason (for example, when upgrading), all the notifications are lost. It would be nice if the app could restore the previous notifications after starting up.

This was originally suggested in #106.

**Implementation:** The app already knows which notifications are active at any time. This information is available in the hash map `NotificationTray.active`. This hash map could be serialized and stored in a SharedPreference, then restored at startup.

**Comment by DanielKaparunakis** [comment]
I would like to work on this. I was trying to see if I could replicate the issue but I was not able to. I set a reminder, turned the phone off, then turned it back on, waited for the reminder to show up and it did. Is there something I am missing?

**Comment by woj-tek** [comment]
OK, steps to reproduce it:
* create a habit (let's say it's 10:00am)
* set notification for 10:05am
* wait for the notification to show up
* when the notification is shown, reboot your phone

expected result: notification should be displayed after phone finished booting up

what actually happens: there is no notification.

--

Haven't tested recently if snoozing works across reboots (set notification, notification is displayed, snooze it, rebook your phone, after reboot and snooze time passed notification should be displayed) but I'm fairly certain that it wasn't working previously as well.

**Comment by DanielKaparunakis** [comment]
Okay I was able to reproduce this. I am thinking that a possible solution is storing the HashMap and then accessing it during device startup through a service launched after a receiver receives the boot complete event. Thoughts?

**Comment by iSoron** [comment]
I think that would work fine for persisting notifications across reboots, but probably not after upgrades. Perhaps we could restore the notifications [when the application is created][1]? This would also restore them after the app is forced to stop then launched again.

[1]: https://github.com/iSoron/uhabits/blob/638b3f763cda02dd8d77d1ff0f456ba733d6790e/app/src/main/java/org/isoron/uhabits/HabitsApplication.java#L111-L112

**Comment by iSoron** [comment]
I no longer think this is an important feature. This affects all Android apps, and should be handled by the operating system. There also seems to be very low user demand for this feature.

**Comment by digitalcircuit** [comment]
Some other applications, such as GMail, do recreate notifications after reboot and application upgrade.  I can understand not prioritizing this, however!

And while not ideal, this encourages me to finish my habits if I need to reboot my phone for other reasons (updates, Magisk module changes, etc) :slightly_smiling_face:

**Comment by felixwiemuth** [comment]
Hi, I can see that this was not considered too important, but regarding that I personally would find this quite useful and seeing that others wished to have this too, I'd like to take this up again and volunteer to implement it.

I just solved the same issue for my app [SimpleReminder](https://github.com/felixwiemuth/SimpleReminder), where I want to show due reminders after a reboot when a notification was already shown before the reboot.

I think it can be implemented with quite little effort. If `NotificationTray` is already keeping track of the current notifications, I would implement this feature in the following way:
- Persist the `active` map from `NotificationTray` into the app's SharedPreferences on every change (as a map from habit IDs to `NotificationData`).
- On boot, upgrade or other start of the app, initialize `NotificationTray` by loading the persisted `active` map.
  - Then check for each entry in the map whether the notification is already shown (using the corresponding ID) and only show the notification if it is not already showing. We might want to use `NotificationCompat.Builder.setSilent(true)` so that there is no new sound/vibration for this "recreated" notification.

What do you think?

**Comment by iSoron** [comment]
@felixwiemuth PRs are welcome. If this can implemented cleanly, I will merge it.

**Comment by felixwiemuth** [comment]
@iSoron Great, I think it can be implemented cleanly and I started looking at the code in more detail.

I stumbled upon the following and need some brief explanation:

In addition to `NotificationTray`, there is also a class `AndroidNotificationTray` which extends the interface `SystemTray` and has its own `active` map. How are these classes and interfaces related and what is used on Android?

Assuming that the idea was to have a platform-independent `NotificationTray` base class, I implemented serialization in this class, adding an abstract method `persist(serialized : String)` which the implementation must provide (in the Android variant it would be implemented using `SharedPreferences`). But now it rather seems to me that `AndroidNotificationTray` is what is used on Android and where persistence should be implemented.

Please let me know what the intention of these different classes is so that I can implement persistence correctly.

Thanks!

P.S. For serialization I am adding the dependency `org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0` (it is standard for serialization with Kotlin and is very convenient), I hope that is fine?

P.P.S. Finding usages of classes in Android Studio 2021.2.1 does not work reliably for the project, is this because of the deprecated `kotlin-android-extensions` Gradle plugin or can I do anything to make it work?

**Comment by iSoron** [comment]
> In addition to NotificationTray, there is also a class AndroidNotificationTray which extends the interface SystemTray and has its own active map. How are these classes and interfaces related and what is used on Android?

Both are used. `NotificationTray` and `AndroidNotificationTray` could be a single class, but we split them in half to make most of the logic testable on the JVM instead of requiring everything to be tested on the emulator. `NotificationTray` is a pure Java class, and contains most of the logic. `AndroidNotificationTray` depends on Android classes and is as dumb as possible. I think the persistence code should be in `NotificationTray`. The hash map `AndroidNotificationTray.active` no longer appears to be used; I think we just forgot to remove it.

> P.S. For serialization I am adding the dependency org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0 (it is standard for serialization with Kotlin and is very convenient), I hope that is fine?

That's fine.

> P.P.S. Finding usages of classes in Android Studio 2021.2.1 does not work reliably for the project, is this because of the deprecated kotlin-android-extensions Gradle plugin or can I do anything to make it work?

Recently, it seems like the version of Android Studio must match the version of the Android Gradle Plugin (AGP), otherwise you get all sorts of errors. In the `dev` branch we are using AGP 7.3.0-rc01, which was released together with Android Studio Dolphin RC 1 (2021.3.1.14). Could you try that version?

**Comment by felixwiemuth** [comment]
> Both are used. [...] I think the persistence code should be in `NotificationTray`. The hash map `AndroidNotificationTray.active` no longer appears to be used; I think we just forgot to remove it.

Okay; I now also see that `NotificationTray` has a reference to `Preferences` (which then in Android code uses the `SharedPreferencesStorage` I guess), so I'll use that for persistence.

However, a missing piece is how to load the habits from the database, having only loaded their IDs from SharedPreferences. Is there a way to do it from `NotificationTray` or do we have to initialize `NotificationTray` with the loaded `Habit`s? Maybe the latter is cleaner anyway - can you point me to where this is initialized? It seems to be done via `HabitsApplicationComponent` but I am not sure how this works.

> Recently, it seems like the version of Android Studio must match the version of the Android Gradle Plugin (AGP), otherwise you get all sorts of errors. In the `dev` branch we are using AGP 7.3.0-rc01, which was released together with Android Studio Dolphin RC 1 (2021.3.1). Could you try that version?

Ah right... it is actually because of this incompatibility that I temporarily changed the AGP version to 7.2.2, which is the latest compatible with the current release version of Android Studio. This way it compiles, but I get a lot of unresolved references in the IDE. It would be a bit of a hassle for me to also install the new release candidate version, so I'll try to do without for now.

**Comment by felixwiemuth** [comment]
Thanks!

**Comment by felixwiemuth** [comment]
Note that I changed the implementation so that notifications are first added to the active map when the `ShowNotificationTask` is executed, and not when this task is created and scheduled to execute. I guess that this is fine and it is very unlikely that the app stops before the task is run?

This also means that we actually don't have to persist the `shown` field of `NotificationData`, as all notifications added to the `active` map have been shown (or are just about to be shown). I am currently testing this variant (it is a small change) and I think this will be preferable, except anyone sees an advantage of the current version.

**Comment by hockeymikey** [comment]
Just came across this, wish it was implemented. Might have to take a look at it in my free time.
