### ISSUE TITLE
1.6 Roadmap?

### ISSUE THREAD

**Issue by that0n3guy** [iSoron/uhabits#177]
@iSoron What is your plans for the next release? (I'm assuming its going to be 1.6).   I see your dev branch is pretty far ahead of master.

**Comment by iSoron** [comment]
Right now, I am still working on some performance regressions (when compared to 1.5.6) and some issues on pre-lollipop devices. After that is okay, I will publish a new beta version. The long delay between this release and the previous is because the source code went through a major refactoring, and we had very few automated tests back then. We should go back to more regular releases after this one.

**Comment by that0n3guy** [comment]
@iSoron Thanks for the update!

**Comment by TheCodePianist** [comment]
Cool, glad to hear this! Thanks for your efforts.

**Comment by iSoron** [comment]
Loop 1.6.0 (beta) has been published on Google Play. It should appear online in a few hours. You must [become a beta tester][1] in order to download it. Please, let me know if you find any bugs. I will also publish the beta on F-Droid soon.

[1]: https://play.google.com/apps/testing/org.isoron.uhabits

**Comment by woj-tek** [comment]
Is there a release (github) or changelog?

**Comment by iSoron** [comment]
@woj-tek I have just added it to GitHub, with a changelog:
https://github.com/iSoron/uhabits/releases/tag/v1.6.0

**Comment by woj-tek** [comment]
Cool, thanks!

**Comment by woj-tek** [comment]
I've tried installing apk from release page (upgrade from f-droid version) but it failes. Does it use different signing key?

**Comment by licaon-kter** [comment]
@woj-tek Yes, everyone that builds it somewhere has a different build key. 
Export/uninstall/install/import.

**Comment by licaon-kter** [comment]
Once [this](https://gitlab.com/fdroid/fdroiddata/merge_requests/1788) gets merged it takes one day for it to appear in F-Droid.

**Comment by woj-tek** [comment]
I thought that somehow it's the same build and they are not building on their own, but it kinda makes sense as it's not possible to jump from Play to f-droid release and vice versa.

@licaon-kter thanks for keeping track with f-droid :-)
