### ISSUE TITLE
Delay for later option missing from notification menu 

### ISSUE THREAD

**Issue by Loricarriedae** [iSoron/uhabits#1831]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
In reminder notifications there used to be three options to tap: 
"Yes"
"No"
"Later" (can't remember exact word used but it was either Later or Delay) 
In the last few days my notification reminders now only show options for Yes and No and the third option to clear the reminder but schedule a time for it to reappear is missing. This was a very useful feature and I hope it is not permanently removed.

## Steps to reproduce
1. Have a habit set with a reminder notification enabled for specific time
2. At that time, swipe down on the notification bar 
3. Swipe down again on the specific habit notification to view button options
4. See only "Yes" and "No" displayed. Third option to delay is missing.

## System information
 - Phone: Google Pixel 3a
 - Phone Operating System: Android 12
 - App version: 2.1.3

## Screenshots
A screenshot is attached.
![Screenshot_20230914-075448](https://github.com/iSoron/uhabits/assets/145017730/90f1a59b-a345-47f7-ab2f-aac52e606850)

**Comment by unrelentingfox** [comment]
I came here to create an issue for the same. The functionality to delay a reminder was the main reason I chose this app over others. Was this feature intentionally removed or is this a bug?

Phone info:
Google Pixel 6 Pro
Android 13
Uhabits version 2.1.3

**Comment by iSoron** [comment]
Thanks for the bug report. This feature was removed in #1226 because: (i) Android 12 introduced some restrictions that broke our current implementation of this feature; the "Later" button is still available on Android 11 and below; (ii) Android 12 now offers [notification snoozing](https://www.androidpolice.com/snooze-android-notifications-how-to/) for all apps, including Loop, so the feature is redundant.
