### ISSUE TITLE
at-most habit starts at 100% score

### ISSUE THREAD

**Issue by dovahgab** [iSoron/uhabits#1962]
Hi, I'm opening this issue as I find it a functional inconsistence, but feel free to move it.

When a habit is created with type 'at most' (e.g. smoke at most 2 times a day), the habit starts at 100% score even without any data - I would say because it considers no data as 0 smokes and thus fulfilled. This contrasts the general behaviour of the app of starting habits at 0% and gradually increases the score.

Thanks for your work!
Yo

**Comment by dovahgab** [comment]
Hm yeah, don't know if it's possible to change one of the two for this specific type of habit only - otherwise it is not so useful, if it starts from 100% (and there's no easy way of translating it into a at-least version) only workaround, flatten it to a yes/no habit

**Comment by jayb-g** [comment]
@hiqua maybe, in case of _at most_ targets, the target has to be set to 0 internally. If that's how it is then when the data is as close to 0, progress is made, but when data is as far(higher) than _at most_ target, progress should suffer(which is not happening). I tested with sample habit of target at most 10, and entered 50 for each day, the progress is still around 75%. Should be 0%. 

Maybe starting _at most_ measurable habits with default of no data(instead of 0)would help. It would work for _at least_ habits too. Calculate progress only based on data entered, whether 0 or non-zero.

**Comment by hiqua** [comment]
@jayb-g you're talking specifically about the score right? Saying that the score computation should ideally ignore all entries up to the first one entered?

**Comment by jayb-g** [comment]
@hiqua yes, scores in case of _Measurable_ habits. I believe ultimately when it comes to showing progress percentage (circle), its basically a yes or no average same as a _Yes or No_ habit type. 

Score computation should ideally ignore the missing data(instead of defaulting to 0). I know this would not reflect accurate tracking due to missing data but its the best(it would be accurate for the days data is provided for) it can do if data is not provided by user.

**Comment by iSoron** [comment]
Thank you for the bug report, @dovahgab, but this is working as intended.
