### ISSUE TITLE
Add support to Jalali calendar

### ISSUE THREAD

**Issue by armoun** [iSoron/uhabits#209]

**Comment by iSoron** [comment]
I am not familiar with this calendar, so I will not be adding this feature to the app myself, but I will consider pull requests implementing it. The same is true for other alternative calendars.

**Comment by armoun** [comment]
@iSoron 
@ebraminio
`https://github.com/ebraminio/DroidPersianCalendar`

**Comment by iSoron** [comment]
Since the release of the app, there has been very little demand for alternative calendars. Given how we assume the usage of the Gregorian calendar in almost every section of the app, implementing this feature would take considerable effort, and add considerable complexity to our code base. For this reason, I am closing this issue. If the user demand for this feature increases, I will certainly reconsider it.
