### ISSUE TITLE
Show half-cross semi-complete habit option

### ISSUE THREAD

**Issue by arlsr** [iSoron/uhabits#210]
I'd love it if there was an option to show an orange half-cross the first time a habit checkbox is touched (and then mark it as complete the second touch).

This could be used to record that an attempt was made but that it was not fully completed. I think it's important to be able to note that you made an effort and can distinguish between habits you are actively attempting and ones you are ignoring.

Another advantage as a side effect would be that it would be more difficult to accidentally check-off a habit with quick touch enabled.

**Comment by chreekat** [comment]
I would say the most important part of building a habit is making the attempt. So if you have made an attempt, that is good enough to make a full mark in the habit tracker.

Tracking actual progress (chapters read, lessons practiced, words learned) can be done separately!

**Comment by iSoron** [comment]
Thank you for the suggestion, @arlsr, however I have decided not to implement this for yes/no habits, since it would make the interface harder to use, and there has not been enough demand for this feature. For numerical habits, I am planning to let the user choose a target (for example, "read at least 50 pages per day"). Even if the user falls short of the daily target, the number is still recorded, and partial scores are awarded.
