### ISSUE TITLE
[Feature request] Share menu for full backup

### ISSUE THREAD

**Issue by castor-troy** [iSoron/uhabits#212]
For some android apps, there will be a share menu which shows the available apps that we can share the files to. I think if you can include that in the app, we can use other software to export full backup. Currently, I see bluetooth and email. If you can enable third-party app sharing, I could use a number of apps (eg: Whatsapp) etc. to export my full backup.

**Comment by licaon-kter** [comment]
Get Total Commander and save locally. ;)

**Comment by iSoron** [comment]
We are already sharing the file with any app that is willing to receive it. The problem is that most apps will only accept certain types of files, such as pictures. Email and Bluetooth show up on your list because they accept all types of files. Google Drive, Dropbox and WeChat, for example, also show up on the list, if you have them installed.

If you just want a local copy, there is no need to have any third-party app installed. Whenever you export the data, a copy of the generated file is also automatically saved on the SD card, inside the folder Android » data » org.isoron.uhabits.
