### ISSUE TITLE
I want to create a habit of washing clothes every Saturday, What do I do?

### ISSUE THREAD

**Issue by santosh** [iSoron/uhabits#213]
So I downloaded this app on 27-11-2016 (DD-MM-YYYY), which is Sunday. 

I started playing around the app creating habits to track. I'm very lazy and skip washing my clothes. I added a **Habit** to **Wash Clothes** every week; that's what anyone would have done to do it. Here's the screenshot:
![screenshot_20161127-113800](https://cloud.githubusercontent.com/assets/1515991/20645989/5a6dd5ac-b496-11e6-9cdd-1d56d0a7c3fb.png)

But this doesn't works (at least seems) as expected. Here's the another screenshot:
![img_20161127_114535](https://cloud.githubusercontent.com/assets/1515991/20646009/0b29642e-b497-11e6-83c9-5d57967e470c.jpg)

As you can see, the task added repeats every Sunday.
If we say this more technically, if you create a habit which repeats every week, the week starts the day you create the habit.

So my final question is: _Do I need to wait for next Saturday to create my task of washing clothes every Saturday?_

**Comment by licaon-kter** [comment]
Maybe rename this to "Add week day selection for weekly habit"

**Comment by iSoron** [comment]
> As you can see, the task added repeats every Sunday

The graph is showing one dot for every week because the frequency selected (on the upper right corner of the graph) is weekly. You can change that frequency to daily, monthly, etc. This only affects the score graph, not the frequency of the habit.

> Do I need to wait for next Saturday to create my task of washing clothes every Saturday?

No, you can just create the habits right now, and wait until Saturday to add your first checkmark. The day the habit was created is not related to anything else in the app. In fact, we don't even keep track of when each habit was added.
