### ISSUE TITLE
RTL-Layout: Alarm clock setting misplaced when editing habit

### ISSUE THREAD

**Issue by fin0** [iSoron/uhabits#292]
In RTL-layout, the alarm clock setting (in my case "off" ) is way too far left and collides with the "edit-arrow" of the row.

**Comment by iSoron** [comment]
Setting the system language to an actual RTL language, such as Arabic, does not trigger this. I could only reproduce this issue by setting the language to English then enabling "Force RTL layout" on developer settings. Developer options, such as this one, may cause many other issues, and therefore are not officially supported. If this issue is present in some actual RTL language, please let me know and I will reopen it.

**Comment by fin0** [comment]
Aha ok! Should have tried to reproduce this myself with an actual RTL-language before opening an issue. You are right with the comment on the developer options. Thanks!
