### ISSUE TITLE
Sort by value makes uhabits incredibly slow

### ISSUE THREAD

**Issue by bdambdam** [iSoron/uhabits#297]
Starting 1.7.0 the UI became almost unusable when using the new feature sort by value. I have 30 habits on my octa-core android 7 smartphone. After activating sort by value it takes 35 seconds for the list to appear. 
It shows "You have no active habits" for these 35 seconds. With "sort manually" activated it takes 2 seconds. 
I have "remove finished habits" activated, and it takes another 5 seconds to mark one line in uhabits as finished. 
I love these two features (sort by value and remove done) but these make the tool almost unusable. 

I tried to repair the db. I reinstalled the app. Nothing helped. 

Other than that it's a great tool. Thank you!

**Comment by iSoron** [comment]
Thank you for the feedback, @bdambdam. This is the main reason why this version of the app is still in beta. Could you install the following version and check if the performance is acceptable on your phone?

http://files.loophabits.org/loop-1.7.2-bug297.apk

**Comment by bdambdam** [comment]
Wow, impressive speed @iSoron . So yes, it's much faster. Almost at the 1.6.x speed, which is amazing. Startup takes now around 2 seconds instead of 35. Checking individual entries is faster as well.

**Comment by bdambdam** [comment]
It is much faster indeed, but this version (1.7.3) doesn't reload the whole list in the next morning with "Remove Completed" activated.

**Comment by iSoron** [comment]
Glad to know that the performance problems are gone. The issue of reloading the list will be solved in the next version (1.7.4) which will be out in a few days.

PS: If you still have the APK from the link above installed, please make a backup of your data, uninstall it, and then install the app again from Google Play (or F-Droid), otherwise you will not receive the next updates automatically.
