### ISSUE TITLE
Notification opens summary page

### ISSUE THREAD

**Issue by kpeckett** [iSoron/uhabits#305]
I often forget to update the tracker, and would just tap the notification as is, and use the main interface to mark habits as done.

A recent update seems to have made the action for tapping a notification load the summary page for the habit and not the main page as it used to.

Is this a bug or a feature?

**Comment by iSoron** [comment]
Yes, this is an intended feature. Now we show the statistics page for the habit, but we no longer automatically dismiss the notification. If you want to open the main screen of the app, you can still tap the notification and then tap the back arrow (top left of the screen).

**Comment by martinwake** [comment]
Would you consider instead adding an option to mark the habit as done from the statistics page? When I want to respond to a reminder it's usually because I have done the habit and need to mark it "done". It's frustrating to have to do the extra actions (tap back arrow) rather than being able to check the habit straight away.

I don't want to assume that my use of the app is typical, but I use the main page much more often than the summary page because that's where I check off my habits. If I want to see the summary page I can always find that easily by launching the app.
