### ISSUE TITLE
Make an option to force english locale

### ISSUE THREAD

**Issue by dalecarlian** [iSoron/uhabits#310]
The Swedish locale contains lots of grammatical errors and other flaws which make the app unusuable. Lots of stuff that doesn't make any sense any more.

Suggestion is to have an option where you can force the app to English locale than forcing the user to the system locale.

**Comment by licaon-kter** [comment]
Why not fix the translation then?

**Comment by dalecarlian** [comment]
@licaon-kter I can't fix it and there is a lot of translations that needs to be corrected and done.

**Comment by licaon-kter** [comment]
Just edit the file and make a Pull Requesh, that's what we all do.

The language switch is not "in character", what Google app has it?

**Comment by dalecarlian** [comment]
@licaon-kter I did translate this app earlier, but I haven't got the time to do this lately. 
I've seen a lot of apps that has the option to change the locale. Even if I google it +stackoverflow I find a lot of solutions for this.

**Comment by dalecarlian** [comment]
OK, did a quick review. Done. https://crowdin.com/proofread/loop-habit-tracker/1/en-sv

**Comment by iSoron** [comment]
@dalecarlian Thank you for the translations. I made you a proofreader at our translation website, which allows you to disapprove the bad translations and approve good ones.

@licaon-kter We now have a dedicated translation platform at http://translate.loophabits.org/ The files here on GitHub are automatically generated by it. For that reason, I am asking people to translate it over there, instead of sending pull requests.

**Comment by licaon-kter** [comment]
Great, I did not bother to look that up since just editing the file here is so easy. ;)
