### ISSUE TITLE
"No" action to dismiss a notification if "Make notifications sticky" setting is checked

### ISSUE THREAD

**Issue by rsri** [iSoron/uhabits#319]
For persisted notifications, if a user wants to dismiss a particular notification (For example, waking up early habit on a Sunday), with the current version, it's impossible. It would be better to have a "No" action for persisted notifications that performs the same action as swiping a non-persisted notification. If the idea is approved, I can take up this tiny feature and finish it. :)

**Comment by iSoron** [comment]
This is related to #307. I think it's okay to add a "no" action to all notifications, even if the notifications are not sticky. I would like this button to **remove** the checkmark, though, instead of simply dismissing the notification.

If you need any help implementing this, just let me know. We also have a Slack channel, for more real-time discussions. Send an email to dev@loophabits.org if you would like an invitation.

**Comment by rsri** [comment]
Can you please explain the difference between dismissing notification and remove a checkmark? If a habit has been checked, the app doesn't show notification for the same. So dismissing notification implicitly means removing a checkmark right? Am I missing something?

**Comment by iSoron** [comment]
In theory, we never show a notification when there is already a checkmark, so dismissing is the same as removing. In practice, strange things can happen, and it's quite possible that the notification is still showing up, even though a checkmark is present. In these cases, the expected behavior would be for the checkmark to disappear.

In the past, we had a bug where pressing "yes" caused the checkmark to disappear, because we were blindly toggling the checkmark, trusting that no checkmark was not there.

**Comment by jindalshreyansh** [comment]
Please add this feature. I keep the habit notification persistent because I dont want to clear it when I press clear all. But if I fail to do the habit, I have to press check, then open app and uncheck.

**Comment by iSoron** [comment]
This has been implemented and will be available in Loop 1.8.
