### ISSUE TITLE
Mark previous day habit has done

### ISSUE THREAD

**Issue by pierrrrrrre** [iSoron/uhabits#32]
Hi!

First of all, thanks for developing this great app!

Could it be possible to add one or two days in the past in the main window, so that if you forgot to tick an activity the day before, you can still do it in the morning of the following day for instance?

I'm used to check my habits done for the day the following morning, and I realized it's currently impossible to do so with current version of the app (1.2.0 in F-Droid).

Thanks!

**Comment by iSoron** [comment]
Thanks for using the app. The number of days on the main screen depends on the screen resolution of your phone. If you put your phone in landscape mode, you can also see some additional days. Just out of curiosity, what phone are you using? The app was supposed at least two or three days, in any case, so that might be a bug.

The newest version of the app is 1.3.0, and it includes a new history editor.
It might take a few days for it to show up in F-Droid.

**Comment by pierrrrrrre** [comment]
Thanks for the quick answer!

I forgot to attach a screenshot and to provide info about my phone, sorry about that!

It's a Samsung Galaxy S3, I'm using Cyanogen Mod with Android 6 on it, and it looks like this:

![screenshot_20160314-102644](https://cloud.githubusercontent.com/assets/512471/13733585/aed3409c-e9cf-11e5-9542-da45675d6f8b.png)

Good to know v1.3.0 has an option to edit history! That's actually exactly what I wanted :)

I guess we can close this issue then. Thanks again!
