### ISSUE TITLE
Feature Request: Disable Tracker

### ISSUE THREAD

**Issue by haopei** [iSoron/uhabits#323]
Hello everyone,

Once again, I would like to say that this has changed my life. Please allow me to request this feature which I believe would make this app even more applicable to life.

I would like to request 'disable tracker' feature which would allow users to disable the app from sending prompts with an option to re-enable the app in the near future. This is useful in situations where we want to take a break from the pop ups but we would not wish to uninstall the app or to lose our data. 

Thank you for reading!

**Comment by TruffelNL** [comment]
Do you only want the notifications to stop or do you want to have a break from your habits as well? If it is the latter, you defeat the purpose of the app a little.

**Comment by artem-p** [comment]
+1 for disable/pause feature. It may be useful on vacation when I can't do my regular habits.

**Comment by vinayneekhra** [comment]
Hi, 
Did you mean taking a break from a particular habit so that it doesn't affect user's habit's score?
This is a desirable feature, however the way the app calculates the score is based on past activity (taking  decreasing weight of past performance), so without changing the core of the app, I think it wouldn't be possible to 'pause' the habits without score getting affected.

There is a feature to 'archive' the habits, user may also try to disable notification for a particular habit. (However if the activity is not done that day, it will result in decreasing the habit score).

@haopei said
> "I would like to request 'disable tracker' feature which would allow users to disable the app from sending prompts with an option to re-enable the app in the near future"

This may be a feature request, if I understand correctly, you meant 'disable notifications for a given period of time for a particular habit and/or for every habit'?

One option could be when user archives the habit, there may be an option to ask the time to unarchive the habit.

**Comment by iSoron** [comment]
Thank you for the suggestion, @haopei. I am not planning to add this feature to the app, since Android already allows you to disable all the notifications for a given app. You can find the instructions for your specific version of Android with a quick Google Search. For Lollipop and Marshmallow, [see this link](https://www.howtogeek.com/204187/how-to-disable-app-notifications-in-android/). Newer versions of Android make this process even easier.

**Comment by c33s** [comment]
what a pitty. from my usecase it would not only be to disable all notifications, it would be to pause a tracker.
