### ISSUE TITLE
Update from "X times in 7 days" to "X times a week" 

### ISSUE THREAD

**Issue by charlesdurham** [iSoron/uhabits#366]
7 days is recognized as a week only when it's once a week and the messaging is "Every week" in this situation. It'd be nice if 7 days was always translated to a week.

**Comment by charlesdurham** [comment]
I don't think [this](https://github.com/iSoron/uhabits/blob/dev/uhabits-android/src/main/java/org/isoron/uhabits/activities/habits/show/views/SubtitleCard.java#L104) is localized correctly. It enforces the ordering of the words in the sentence, which can be locale sensitive.

**Comment by iSoron** [comment]
Hi @charlesdurham, the wording is intentional to make it clear that we are using a rolling period of 7 days, instead of the usual calendar week (Sunday to Saturday). Regarding the localization, I was also worried about that at first, but the app has now been translated to more than 30 languages, and, so far, no translators complained about that fixed structure.
