### ISSUE TITLE
Don't show the snackbar when a new habit is created

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [iSoron/uhabits#422]
Currently, when a new habit is created, a snackbar is shown saying "A habit has been created" (translated).

I think that this is a bad design because:

1. The user can clearly see the new habit appear in the list.
2. The action isn't volatile (e.g. doesn't depend on the network), it is expected to be successfully executed 100% of the time, so there isn't really much information in explicitly saying that it is successful (it could, for example, display when the creation has failed, which is a much more valuable information, since the odds are much smaller).
3. It doesn't have any buttons, such as "Undo", so it doesn't have any essential actions bundled with it.
4. It distracts the user (it confused me, because I didn't expect a notification for something so trivial (other apps don't do it, so it isn't the expected behavior)).

Proposed change would be to not display the snackbar, unless the creation of a habit failed.

**Comment by PatrickKuehn1994** [comment]
Hey @aleksandar-stefanovic, I think this is not a good idea, because the user can't see a new habit directly, if he has more habits than can be displayed on the screen.

This could be better, if the new habit is added at the top of the list and has a different background for a few seconds. In that case I would also suggest to remove the snackbar "A habit has been created" .

**Comment by iSoron** [comment]
Thank you for the suggestion, but I like to err on the side of too much feedback rather than the opposite, so I am not planning on changing this.
