### ISSUE TITLE
Widgets don't work for numerical habits

### ISSUE THREAD

**Issue by jakedp7** [iSoron/uhabits#425]
The current numerical habit implementation doesn't include functioning widgets. Before the feature can be made public, this must be fixed - most importantly, for CheckmarkWidget.

**Comment by jakedp7** [comment]
@iSoron Just following up, looking to hear back about the design questions above.

**Comment by iSoron** [comment]
Sorry for the long delay, Jake. Note that the constructor of `CheckmarkWidget` has a `Habit` object as parameter. The information you want can be accessed from this object. More specifically, you should do `habit.targetValue` or `habit.targetType`.   Since we may have tens of thousands of `Checkmark` instances in memory, these objects contain only very minimal information.

Please feel free to submit a pull request, even if your patch is still work-in-progress. We can keep discussing the technical details on the pull request page until your patch is ready for merging.

**Comment by iSoron** [comment]
This will be fixed when #42 is completed.
