### ISSUE TITLE
Widget with multiple habits

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#45]
A widget that contains all habits as a list would be very handy to tick habits off, like it's already implemented in [HabitBull](https://play.google.com/store/apps/details?id=com.oristats.habitbull) and shown [here](http://i.imgur.com/CQGFOIn.png).

**Comment by flowgunso** [comment]
The priority on this feature should be raised, it improves usability.

**Comment by mr-flibble** [comment]
I also think that this is an important feature that the application is missing.

**Comment by yetanothernerdk** [comment]
This will be a great feature, agree with @flowgunso, priority should be raised.

**Comment by vyu1** [comment]
Hi all, I haven't contributed to this project before, but is it okay if I try to work on doing this? I've found this feature lacking since first installing the app.

**Comment by vyu1** [comment]
Hi all, I haven't contributed to this project before, but is it okay if I can start working on this? I've found this feature lacking since first installing the app.

**Comment by iSoron** [comment]
Hi @vyu1, pull requests are very welcome. How are you planning to make the checkmark widget support multiple habits? Widgets are very limited on Android, but one thing we could use is the [StackView](http://www.broculos.net/2011/12/android-101-how-to-create-stackview.html) layout. If you have any other ideas, let me know.

**Comment by vyu1** [comment]
@iSoron I was thinking of making a new ListView layout (widgets don't support `RecyclerViews`) that looks similar to the image @sojusnik posted above, http://i.imgur.com/CQGFOIn.png and to `HabitsActivity`.
However, using a `StackView` could also be interesting, and I'm open to anyone's input on which I should try to implement.

**Comment by woj-tek** [comment]
+1

A widget with a view similar to main app, with possibility to select which habits to display (this would go hand in hand with #325)

**Comment by iSoron** [comment]
Thanks to @vyu1, it is now possible to stack multiple widgets together. This works not only for the checkmark widget, but for any other widget we currently have available. Please see the screenshot below.

At this time, I am not planning to add a widget similar to the app's main screen. This is mainly due to Android limitations. I already said this before, but Android widgets are truly limited on what they can do, or even in what they can look like. We already employ a number of hacks to work around these limitations and to make our current widgets look and behave as well as they do. I don't think it would be possible to recreate the main app screen on widgets. Even if we somehow managed to do it, I would expect it to be very sluggish, and have poor usability. That being said, anyone is free to try, of course, and I would be glad to review such a patch.

![screenshot_1529197063](https://user-images.githubusercontent.com/4699657/41503680-89cb5dc0-719f-11e8-95d6-c5a6ac480caa.png)
