### ISSUE TITLE
Theme-related Issue

### ISSUE THREAD

**Issue by YohananDiamond** [iSoron/uhabits#451]
I couldn't find a good title for this.
1. **_OLED-friendly theme:_** all the background elements could be black, being more battery-friendly to OLED Screen Devices.
2. **_Custom themes:_** the user could choose the color of the **action bar**, of the **background** and of the **habit cards**.
3. **_Scheduled Themes:_** for example, schedule a day theme, an afternoon theme and a night theme.

**Comment by iSoron** [comment]
Thank you for the suggestion, @YohananDiamond. Loop already has an OLED-friendly theme; it can be activated in the settings. We also have a day theme and a night theme, and it's already fairly easy to switch between the two. I am not planning to implement custom themes, since it would add significant complexity to our source code and user interface.
