### ISSUE TITLE
Color Naming

### ISSUE THREAD

**Issue by YohananDiamond** [iSoron/uhabits#458]
Maybe the colors could optionally receive names for, when an habit is open, it shows the color and its name.
This can be good for helping the users to memorize their color-coding. I tried to do one but I am struggling myself having to open a separated app just to get the names related to each color.

**Comment by iSoron** [comment]
@YohananDiamond Thank you for the suggestion. Naming the colors is complicated because we would need to update translations in all 30+ languages that the app is available. It would also restrict our ability to create new color palettes. However, I think your use case would be covered by #31. Instead of associating all "exercise" habits to the color green, for example, you could simply create a tag call "Exercise".
