### ISSUE TITLE
Break days on non-daily habits should not decrease the strength

### ISSUE THREAD

**Issue by chennemann** [iSoron/uhabits#463]
I think it's a bit counter intuitive and even demotivating that the strength goes down for days on which you don't have to complete the habit (let's call them break-days).

It's best explained with a picture:  
![](https://i.imgur.com/GoOBZCX.jpg)

As you can see the habit is completed every time it should be completed and the streak is ongoing. Nevertheless I have to rebuild the strength every week again because it goes down on Saturdays and Sundays. 

I don't know how the algorithm currently works but I would propose that break-days should neither increase nor decrease the strength of a habit. 

If my proposed solution is desirable I could work on implementing this change. So please let me know if I should start working on that.

**Comment by chennemann** [comment]
I just implemented a working change. But I'm actually not happy with my approach. 
It works for my use case but it is quite inflexible so we should look for a different approach. Maybe someone has an idea that would diminish the nasty double check and that also works with numerical habits.

**Comment by Anshoe** [comment]
Agreed

**Comment by jimfarrand** [comment]
I built the current dev branch and it looks like the behaviour is a little different from the version in the play store.  With regards to the score calculation, implicit ticks for break days are considered NOT DONE on the Play Store version, but are considered DONE on the dev version.

The dev version behaviour seems a lot more sensible to me than the Play Store version.  However, it's not quite what @chennemann originally proposed, which is that break days should neither increase nor decrease the score.  That said, although I prefer the original suggestion, I could live with the behaviour in the dev branch.

Is it worth me implementing the change as originally requested, or is there now consensus that the dev behaviour is correct?  I'm happy to try to make the change if it will be accepted.  Otherwise maybe we should close this issue?

**Comment by chennemann** [comment]
maybe you can have a look at my current implementation that I referenced in this issue and you find a more flexible solution than I did. I actually don't like both versions. neither increasing nor decreasing should be the actual behavior because you neither work on building your habit nor are you neglecting it.

**Comment by jimfarrand** [comment]
Work in progress.  Tests need to be updated.

The interface to Checkmark and friends is kinda... not good.  It's not really providing any encapsulation and so callers to getValue() and friends have to be hyper-aware of the implementation details in other parts of the code.

But fixing that looks like a real bug job that is going to break anyone else that has WIP so I don't think I should tackle it in the scope of this issue.

**Comment by jimfarrand** [comment]
Though having said that, I'm tempted to push the conversion to a numerical value into Checkmark (or at least pull it out and put it somewhere where it can be reused)

**Comment by iSoron** [comment]
@jimfarrand For discussion about implementation details of a particular feature, please open a WIP pull request.

**Comment by iSoron** [comment]
> The dev version behaviour seems a lot more sensible to me than the Play Store version. However, it's not quite what @chennemann originally proposed, which is that break days should neither increase nor decrease the score. That said, although I prefer the original suggestion, I could live with the behaviour in the dev branch.

This is indeed the case; the score now keeps slowly increasing over break days, instead of slowly decreasing. I would expect most users to find this acceptable, so I am closing this issue. These changes will ship on Loop 1.8.
