### ISSUE TITLE
Make habit list horizontally scrollable

### ISSUE THREAD

**Issue by chennemann** [iSoron/uhabits#466]
I don't know whether this was already suggested but I think it could be a nice thing to make the habit list horizontally scrollable so that you are able to see more than just the last five days. 

Maybe the scrolling should be a little bit harder to trigger. What I mean by that is that it starts not simultaneously with the finger movement but with a bit of a threshold.

**Comment by iSoron** [comment]
@chennemann You can already scroll the list horizontally by dragging the header (the grey part on the top which shows the days of the week). I agree that this is not very discoverable. Please feel free to build a prototype where the list can be dragged horizontally anywhere. As you mentioned, getting this right might be a little complicated.

**Comment by chennemann** [comment]
Awesome. I didn't know that. The discoverability of my solution would not be better I guess. 

I think we should just add another "did you know" to promote this feature.

It should show up as soon as the user has one habit checked more than the visible days ago. 

What do you think about that?

**Comment by ImAnnoying2** [comment]
Maybe an option to launch the app in landscape by default could be a quick solution for those that have fewer habits but want to get motivated by streaks. Or maybe list habit streaks vertically instead of horizontally, also as an option?

**Comment by tonypuglieso** [comment]
Hello other posible solutions, Add a symbol so that the user knows that it can be moved and / or a smaller mode, so that in the vertical mode more days are filled.

![loop habits sketch](https://user-images.githubusercontent.com/52177646/83360864-f1f57180-a35a-11ea-9837-2bdbfb7d8f51.png)

I understand that a minimal mode, it can be difficult to press such small buttons. That could be a problem. But it would be an interesting option that someone can manually activate in the settings.
