### ISSUE TITLE
Allow user to create groups of habits

### ISSUE THREAD

**Issue by malnvenshorn** [iSoron/uhabits#495]
I really like your app, but I'm missing this special feature: (sub-) tasks for habits. This feature would really help to manage habits like:

- Stretching exercises
    - Morning
    - Lunch break
    - Evening
- Learn Japanese
    - Review vocab
    - Complete grammar lesson

I'd really like to break down habits in tasks and be able to check them separately.

**Comment by hiqua** [comment]
Can you expand on the advantages of having such a structure compared with having:

* stretching exercises: morning
* stretching exercises: lunch break
* stretching exercises: evening
* learn Japanese: review vocab
* learn Japanese: complete grammar lesson

That's what I currently do in such cases. The main shortcoming I see is that I cannot compute the stats about the main task directly (in your example, I couldn't get the stats about the "stretching" metatask without computing them myself). Are there others which make you want such a feature?

**Comment by MohamedKiouaz** [comment]
The other that I see, and that I would really appreciate would be to have logical relation between habits.

For example, in a main task "sport", I would have swimming, bodybuilding, soccer, and more. I physically cannot train 2 sports on a same day without falling apart.
So when one sub-task of the main task "sport" is checked, the others would be in a "passive check" state, and the habit score would not decrease.

Also, thanks for the hard work on this app. I have been using it for more than a year. It is awesome.

**Comment by hiqua** [comment]
Ok I see, in your example of course you could just track the activity `sport`, but I think what would be interesting is to still have minimum requirements for the subtask, e.g.:

* `sport` is some kind of *metatask* and is done at least 3 time per week, including
  * `swimming` at least once a week
  * `bodybuilding` at least once a week
  * `soccer` with no minimum

This *metatask* system is quite different from what the original post meant though.

**Comment by chennemann** [comment]
In my opinion this feature seems to be really hard to implement (how to design an unobtrusive UI; calculating the overall score from all the sub-habits; build additional statistics UI for the meta-habit) while providing little value over all.

I see your point why this might come in handy but in my opinion the grouping can easily be achieved by assigning the same colour and sorting by colour.

**Comment by malnvenshorn** [comment]
Don't automatically calculate a score for the main task from its sub-tasks. Every (sub)-task has it's own statistic and the main task has to be ticked of by hand.

> I see your point why this might come in handy but in my opinion the grouping can easily be achieved by assigning the same colour and sorting by colour.

If you do that you run out of colors pretty fast and additional colors won't help because the need to be easily distinguishable.

**Comment by chennemann** [comment]
that means that you would need to check "doing sports" two times? one time because you went to the gym and one time because you completed the group? 
that makes the usability not exactly good. 

and if you handle every single sub habit and the group as its own entity by hand I am not able to see any advantage at all over the current version. 

what I could see working would be a grouping function. so you would be able to assign a habit to a group. the only thing that would do is a visual grouping on the main screen. that actually might be relatively easy to implement and can later be extended to allow for group statistics and such. if that would be enough to solve your problem we should probably close this issue and open a new one with the above mentioned request. 

keep in mind that I'm not the official supporter of this project though.

**Comment by iSoron** [comment]
This feature request is somewhat tricky because most users who request it are actually proposing a particular solution ("to create group habits") to a problem that they have never fully explained. There seems to be at least three perceived problems out there:

* **I want to create groups of habits so that I can better organize the list.** For example, if I am not particularly interested in some group of habits right now, I could collapse that folder and focus on something else. Perhaps I could also move the folder, archive it or edit it more easily. Some users also suggest creating multiple lists of habits instead of folders, but the underlying problem seems to be the same -- they don't think the current interface is organized enough.

* **I want to create groups of habits so that I can see their combined performance.** For example, if I have three habits related to Japanese learning, I might want to know how are these habits progressing, not individually, but as a group. This is essentially #51.

* **I want to group multiple habits so that the app can automatically calculate the score of this combined group according to some complicated rule.** For example, if I would like to receive a checkmark whenever I perform any two of three possible sports activities within a week. I still want to track each activity individually, but I don't want to spend time calculating the combined score manually. This was first proposed in #191.

I am still not convinced that the first problem is that serious. We already have colors, in addition to different sorting and filtering methods. The layout proposed by @hiqua works very well for long lists. If anyone wants to create some compelling user interface concepts, I could change my mind.

The second problem is much more serious to me, and I would even categorize it as one of the main current limitations of the app, but we already have an issue for that (#51).

The third one looks somewhat interesting, but I would assume only a tiny fraction of users would be interested in it and it would significantly complicate the code. Coming up with an interface for even describing these rules also looks pretty hard. If the rules are very simple (say, the percentage of completed habits in the group), I would be fine with it. This could be implemented in #31 -- after creating a tag, the tag could appear as a "read-only habit" in the main screen, and its score would just be an average.

**Comment by malnvenshorn** [comment]
> that means that you would need to check "doing sports" two times? one time because you went to the gym and one time because you completed the group?

I guess it would be nice that the main-task is checked automatically depending on constraints, but it is not that important for me. The real advantage with this would come with complex rules and this might be hard to implement.

> and if you handle every single sub habit and the group as its own entity by hand I am not able to see any advantage at all over the current version.

With just grouping you don't have a statistic!

What I suggest is actually a combination of:

> **I want to create groups of habits so that I can better organize the list.**

> **I want to create groups of habits so that I can see their combined performance.**

@iSoron 

> I am still not convinced that the first problem is that serious. We already have colors, in addition to different sorting and filtering methods. The layout proposed by @hiqua works very well for long lists.

I just quote myself: "If you do that you run out of colors pretty fast and additional colors won't help because they need to be easily distinguishable."

Another issue is the limited space for the text, you have two lines and on small screens the text is often cut off if you are using long names as suggested by @hiqua . This makes it confusing.

**Comment by MohamedKiouaz** [comment]
@iSoron I can imagine a somehow simple way to design and implement this.

1. A task can reference another task as it's main task. This would be a single input.
2. A task can have a rule : check if at least X sub-tasks are checked. The number N would be another input.
3. A task have a rule about how to behave with the main task. This would be limited to "weak check if main task is checked" (score is frozen for that day) and "no interaction with main task".  This would be the 3rd input.

Basically, if this is codded in a generic way that you can create sub-sub-tasks and more. You would be able to create complex rules with basically minimal UI.

The difference between this and #31 is that you can check a main task even if a sub task is not checked : I did boxing today, so I check Sport, so my score goes higher, but since Sport is checked, the sub-tasks Soccer, Running and Swimming are frozen, their score does not get lower. I never do Boxing, that's why I do not have an habit, but I wanted to try it.

The main problem that I have today the following one : what motivates me is seeing the calendar with checks and grey checks, with a score that goes higher every week, and not being able to group habits makes scoring pointless in some situations.
1. If I create two tasks : Sport: Running and Sport: Swimming. I have to decide how much swimming and how much running I want to do per week, and I will have to stick to it for a long time (in my case, years) to see both scores increase. If I don't, I only go Running for a month because I am far from my swimming pool, I will see my Swimming score decrease, with red crosses on the last week.
2. I create only a task Sport, I loose track of what sport I am doing (that's what I am doing). But then I loose motivation to do Swimming (I don't have a habit for score).

It makes sense for basically anything, what should I do if I have 2 tasks "learn Japanese: review vocab" and "learn Japanese: complete grammar lesson" like said before. If I go on a trip to Japan, those 2 tasks are going to go down because I didn't "complete grammar lesson" ? Or should I just check them both ? Probably not, a trip to Japan is not a "grammar lesson". But it is still part of "learn Japanese". So a group habit "Learn Japanese" should be checked, and go higher, while sub-tasks are grey checked and score stay frozen.

Thanks for the hardwork @iSoron on this app, it has been a life changing for me. I am very excited about the numerical habits of the next release.

**Comment by chennemann** [comment]
@MohamedKiouaz I very much like this idea. The only really complicated part (for the first working version) would be the implementation of your second point. creating sophisticated rules with subtasks.

I imagine that to be quite complicated because every sub task can have different goals. 

1: complete 4 times in a week
2: complete 2 times in 2 weeks

How could the grouping rule look like?

1: check when any subtask is checked (probably the only feasible solution)
2: check when subtasks are checked X times in X days (maybe)

@iSoron What do you think of this solution. with this approach we could implement the base for all three requirements at once. In the beginning it would provide mostly a solution for the third feature but I can imagine it to be relatively easy to implement a grouping ui for feature 1. the statistics as requested in feature 2 would be basically for free because it will be derived from the checked state of the main task which is known.

**Comment by iSoron** [comment]
@chennemann I think this might work. Are you interested in implementing it? I would suggest starting from the core classes (org.isoron.uhabits.core.models) and dealing with the UI later. Feel free to submit a work-in-progress pull request, so we can discuss the implementation.

**Comment by finedust** [comment]
I'm with @MohamedKiouaz, that would be a flexible and simple solution, but a couple of potential issues came to my mind:

1. This would allow a large number of nested tasks and the score computation will be cumbersome since the relation between parent and child is two-way.
2. In fact this is a consideration: we would need to compute the score of every task of the group (at least. Here group means a parent and all its children) even if we need only a child's score.

My solution to the first point is to allow only one level of dependency (a task cannot be both a parent and a child) because I think that one of the main strenghts of this app is the immediacy and for the majority of the use cases one will be enough. This approach will be also easier to implement because requires only to track if a task has a parent (and which obviously, see below).
Let me explain the second point: if a child may be frozen (for that day) by the parent's check, we need to compute that firstly and to do so we need all of it's children. Since this forces us to compute the whole group's scores we could do something like this:

1. Detect the group in which the task is located (regardless of its role) *
2. Check the parent if at least N of it's children are checked
3. Freeze the children that require to do so

\* Note that this only requires that child tasks reference the parent, without the parent beeing aware of it's children. A static assigment will cause a lot of potential troubles when deleting, moving or adding tasks.

With this approach the changes are relatively small:

- Add an optional reference to a parent task, and the choice freeze/not freeze when parent is checked
- Detect the groups before performing some actions (UI included)
- Add a threshold value to the parent to be auto-checked (I propose to default this to 1)
- Calculate the checkmarks of the whole group instead of the single task

To conclude: for the UI we could just show the children task nested below the parent, a bit shifted to the right.

What do you think? Does this proposal summarize the main problems in an intuitive and easy solution?

**Comment by MohamedKiouaz** [comment]
Hi guys,

Thanks for the replies. I would love to contribute but I have 0 background in Android development. I have a Ryzen CPU so I could not install Android Studio on my computer.

Do you know any way to contribute ? Maybe only using the core of the software and a JVM ?

**Comment by rancidfrog** [comment]
This would be great to have group or sub habits.
For example,
this todo list open source app has sub-tasks which correspond to what is needed:
https://github.com/SecUSo/privacy-friendly-todo-list

 ![](https://i.imgur.com/3hyeqFV.jpg)

![](https://i.imgur.com/MT72mAm.jpg)

![](https://i.imgur.com/uSjuJ7t.jpg)

![](https://i.imgur.com/nwj7kc1.jpg)
