### ISSUE TITLE
Allow user to specify what time does the day begin

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#50]
Would be very hand to specify the beginning of the day, because sometimes people forget to tick off habits before midnight.

**Comment by iSoron** [comment]
I am not sure I understand the problem. Currently, if a reminder appears at night, but you neglect it until next morning, pressing "check" on the reminder will add a checkmark on the original day. That is, it does not matter when did you press "check" on the reminder; the checkmark should always appear on the day that the reminder was created. If this is not happening, then it's a bug. Please, feel free to reopen the issue in that case.

**Comment by sojusnik** [comment]
My proposal was actually related to the habits in the main window and the individual habit widget, not the reminder.

From a psychological point of view, a new day starts after one wakes up and not after midnight. So therefore it should be possible to tick off habits some hours after midnight, while they take into account the current day, not the next one.

**Comment by iSoron** [comment]
Okay, I see how could this feature be useful for the widget widget, so I am reopening the issue. For the main window, however, even though a new column will appear after midnight, you are still free to make changes to any of the previous columns. How would this feature be useful, then?

**Comment by sojusnik** [comment]
Yes, it's actually related to the checkmark widget and for the, hopefully soon implemented, [habit list widget](https://github.com/iSoron/uhabits/issues/45).

**Comment by aleksejrs** [comment]
> For the main window, however, even though a new column will appear after midnight, you are still free to make changes to any of the previous columns.

True, but you have to pay attention to the column date.  Although I can notice it because the new column is empty, it may seem to be so because it has not loaded yet.

**Comment by nj999** [comment]
hello... I have just downloaded this app and like it for its simplicity. Thank you for building this app. Just to add my comments and request feature i have created my github account. :)

I also second this feature of allowing us to chose a start time of the day.

Also, if you could think of start day for the week. I would want week to start on Monday. (not sure today what time the week starts)

**Comment by fin0** [comment]
Would be great!

**Comment by slix** [comment]
I would also love this. I use the 1x1 widgets on my homescreen, but I often finish some habits after midnight. I'd love to see all my completed habits colored on my homescreen at the end of the day instead of seeing them as black.

I've implemented the preferences part of this with a list that lets you select 1-hour times between midnight and noon for the "end of the day".

@iSoron Any tips for implementation? I could make the entire app follow the "end of day" setting by modifying getStartOfDay and related methods in utils to use the setting. (But I'm not sure what that would do to old timestamps if the user changes the setting.)

Or I could modify just the widget, which means not using getToday() anymore after midnight because I'd have to use getValues() to look up the previous day. And using the older score value. (Initially I thought this would be hairier, but I think some of the utils functions would actually make this easy.)

**Comment by iSoron** [comment]
Hi @slix, I think this can be implemented by modifying the time functions in the class DateUtils, as you suggested. It might be enough to just modify the method `getStartOfToday`. Instead of just calling `DateUtils.getLocalTime()`, like you do now, you would need to add some hours to this time.

**Comment by aleksejrs** [comment]
Yesterday, on Dec 01, I started Loop at 23:58. While it was loading, date changed to Dec 02.  The first column's header kept showing Dec 01, but the column showed the Dec 02 states.

**Comment by sojusnik** [comment]
Same here. Closing and opening the app helps. Seems to be a bug.

aleksejrs <notifications@github.com> schrieb am Fr., 2. Dez. 2016, 08:20:

**Comment by tamalbuk** [comment]
> Okay, I see how this feature could be useful for the checkmark widget, so I am reopening the issue. For the main window, however, even though a new column will appear after midnight, you are still free to make changes to any of the previous columns. How would this feature be useful, then?

With Tasker integration, being allowed to specify end/beginning of day becomes a priority IMO. Otherwise it beats the purpose of automatic habit checking. For example, the way I use Tasker is that it does maths on multiple variables, which correspond to different habits, when I start sleep tracking in Sleep As Android. As I _never_ go to bed before midnight, habits checked with Tasker always show on the following day.
