### ISSUE TITLE
Display combined statistics for groups of habits

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#51]
To have the statistics (success rate, current streak and longest streak of a habit) at a glance of all habits would be very helpful.

**Comment by iSoron** [comment]
Thank you for the suggestion. This is somewhat related to issue #31.

**Comment by SuzanaK** [comment]
It would also be great to have the overall statistics in a widget.

**Comment by ysagal** [comment]
This would be particularly useful for a widget to be able to see total progress across all habits at a quick glance.

**Comment by nj999** [comment]
Hello.

I want to add my comments to this thread. We would like to see a combined score/points for one day and track this day over day. Like in google fit you can see that today you have walked 5000 steps and yesterday 4500 steps. So this way we can track progress of all of our goals together. Not sure if this is a new feature or connected to the same comment from ysagal about total progress across all habits. 

But please consider this request/enhancement.

**Comment by chreekat** [comment]
OP didn't explicitly mention "Habit strength", which is the widget/chart I would most like to see. Of course, it may be rather confusing unless one color-codes their habits, since there would be virtually no room for labels.

**Comment by zaheernathani** [comment]
When can we expect this.

**Comment by chennemann** [comment]
@zaheernathani Could you please elaborate on how that could be useful. I have more than 25 habits and seeing them in one graph would be everything but confusing and unorganized.
Is there a specific use-case you need that aggregated view for?

Also regarding the timeline. Since this is an open-source project there is no way to provide you with an ETA. If you want/need that feature you are welcome to submit a PR that implements it.
