### ISSUE TITLE
Use dark theme also in settings window

### ISSUE THREAD

**Issue by szpak** [iSoron/uhabits#545]
Having the dark theme enabled I was surprised to open the settings page and be glared by the while background there. It's not a big issue, but it the back theme could be used consistently.

1.8.5 on Android 10.

**Comment by iSoron** [comment]
Thank you for the feedback, @szpak. I agree that the settings should follow dark theme too. Pull requests are welcome.

**Comment by ayseenver** [comment]
Hi both, 

I was going to try and fix this but on my version of the app (1.7.11), the settings page is dark on night mode. Does it still need fixing?

**Comment by szpak** [comment]
@ayseenver Just tried with 1.8.7 and the settings page is still white. The dark theme ticked in the app.

**Comment by MRoyDroid** [comment]
Hi, @iSoron I've implemented the Dark Theme on Settings Screen. I've created a new Dagger Component (SettingsActivityComponent) for SettingsActivity to get access to the ThemeSwitcher. But I have a confusion, as I've used the HabitsApplicationComponent to build my new SettingsActivityComponent. Is that okay or do I need to create a SettingsApplicationComponent for that?

**Comment by Sunxy88** [comment]
Hi @iSoron We are a group of students trying to contribute on this issue. Since this issues is still open, we suppose we could have a try. However, we are all beginners in android development. We will try our best to do so in a month and it could not be more fantastic if you give us some advices to contribute in more efficient way and to keep codes as elegant as yours ? If we finish this issue sooner than we thought, we would try to solve other issues.
Thank you very much!

**Comment by iSoron** [comment]
Hi @Sunxy88, this issue is still open and pull requests are very welcome. If you would like, please feel free to submit an early version (work-in-progress) of your proposed changes, and we can start a discussion about the implementation.
