### ISSUE TITLE
Habit strength graphs don't reset when switching scale

### ISSUE THREAD

**Issue by matthewsnell** [iSoron/uhabits#575]
When you scroll back the graph I'm day view and then switch to quarter the graph goes blank.

**Comment by iSoron** [comment]
Thank you for the bug report @matthewsnell. Yes, this is a bug. Steps to reproduce:

1. Open the detail page for a habit that has a long history.
2. Switch the score chart to daily intervals, then scroll back in time.
3. Switch to quarter intervals. The graph goes blank (because we scrolled way past the data).

**Comment by alxmjo** [comment]
Just to be clear, I'm understanding that expected behavior on this is:

1. …
2. …
3. Switch to quarter intervals. The graph automatically resets its position such that it's scrolled all the way to the right and "today" (or as close to today as can be reached) is against the right side of the app.

Is that correct?

**Comment by iSoron** [comment]
> Is that correct?

Yes, that's correct. The correct behavior is to reset the position to "today" whenever we change the interval.

**Comment by alxmjo** [comment]
I'd like to take this on, but it's been ages since I've worked with Android. Perhaps you can give me some pointers.

My hope was that I would be able to call `chart.scrollTo(0,0);` from within `doInBackground()` (in `ScoreCard.java`), but I find that this method affects the entire view (i.e., calling `chart.scrollTo(300,0)` shifts the entire view to the left) rather than the scrolling behavior.

Any advice on where I ought to go from here? It seems that the answer is probably in `ScoreChart.java`, but I'm not sure where exactly to look.

**Comment by iSoron** [comment]
@alxmjo You're on the right track. The scrolling behavior in all of our charts in handled by the [ScrollableChart](https://github.com/iSoron/uhabits/blob/8fd8c2802b60c9a1121c0c9432791f6f46fadf63/android/uhabits-android/src/main/java/org/isoron/uhabits/activities/common/views/ScrollableChart.java#L29) class. The current position is stored inside the `ScrollableChart.scroller` object. I suggest that you add a method `ScrollableChart.reset()` which sets the x position to zero, then we can call that method from within `doInBackground`, just after all `chart.setScores(...)`.

Note that after modifying the `scroller` position, you will need to call `scroller.computeOffsetScroll()` and `ScrollableChart.updateDataOffset()`. It may also be easier to just replace `scroller` by a newly created object, instead of modifying its position manually. This is an Android-provided class, and its API is not that great.

**Comment by alxmjo** [comment]
Thank you for the pointers. I've opened a PR.
