### ISSUE TITLE
Highlight habits that need to be done today

### ISSUE THREAD

**Issue by kathytu** [iSoron/uhabits#579]
Hello! I'm new to Loop and I love it so far. Thanks to everyone for working on this app.

I have a question about easily seeing what still needs to be accomplished for today. I know currently you see a light grey "x" for undone habits, and as well I know you can choose to hide completed habits. I'd love to be able to see all my habits at once, but just the ones that need to be done are somehow highlighted or emphasized. 

Suggestions on how this could be implemented:

- the entire row of the habit can be highlighted
- instead of a "x" maybe a more noticeable checkbox
- make the "x" a darker shade of grey

Thanks so much!

**Comment by chennemann** [comment]
Thanks for your suggestions. I agree with you that it's not visible all that well. I like your third suggestion to improve the contrast for a better readability. 
We need to see however what side effects a change like that would have.

**Comment by iSoron** [comment]
Mocks or prototypes showing alternative color schemes are very welcome, but I think it would be hard to make the "x" more noticeable while keeping the interface visually attractive.

Another idea could be showing the habits that need to be done at the top of the list, and the habits that have already been completed at the bottom. That is, we could implement a new sorting method. This should be fairly easy.

**Comment by Vncntmrchl** [comment]
Hello!
My teammates and I are working on this issue. We are students learning Android development so our skills are still limited.
We managed to add a sorting option to show habits completed today at the bottom of the list. We were initially trying to define some kind of "priority ranking" among habits but it turned out a bit too complex.
Moreover, we'd like to make habits completed today a bit less opaque to make it even more obvious that they were already done. We are currently working on this feature but we are having a hard time finding a way to do so (where to change opacity for example).

**Comment by iSoron** [comment]
> We managed to add a sorting option to show habits completed today at the bottom of the list.

Thanks for working on this @Vncntmrchl. I'm looking forward for the pull request.

> We were initially trying to define some kind of "priority ranking" among habits but it turned out a bit too complex.

Could you elaborate on that?

> Moreover, we'd like to make habits completed today a bit less opaque to make it even more obvious that they were already done.

For such visual changes in the user interface, I would recommend creating a mockup first (for example, using GIMP or Photoshop), before spending too much time on the actual Java/Kotlin implementation. I am concerned that making the card less opaque will make it too hard to read.

**Comment by Vncntmrchl** [comment]
Hello again!

I just realized that @hiqua did a really great job at answering this issue. What we did is actually included in his own pull request so I don't think it is necessary for me to do another pull request.
About "priority", I was thinking about ordering habits considering their status (completed or not) and their frequency (whether or  not we still have repetitions to do to consider them "done"), but it turned out tougher than expected.

#660

**Comment by iSoron** [comment]
Fixed by #660. To focus on the habits that need to be done today, please select "Sort by status". Completed habits will be moved to the bottom of the list. This should become available in Loop 2.0. Thanks, @hiqua!
