### ISSUE TITLE
Trying to add widgets when no habits have been created only dims the screen

### ISSUE THREAD

**Issue by alfred4x** [iSoron/uhabits#584]
When i drag the widget from widget menu to the home screen and release it the screen gets a little darker((as it does when "permission to create a widget" dialogue box appears for other app widgets)) but nothing appears on the screen. God bless ya. and good luck.

**Comment by hiqua** [comment]
Can you give more information about which Android / Smartphone you use? Does it always happen? What happens if you use "add automatically"?

Can you use "generate a bug report" from the settings and add the report here (be sure to review it before posting, I don't think any personal info should be there, but we never know).

Thanks!

**Comment by iSoron** [comment]
Thank you for the bug report, @alfred4x. I think the issue being described here is that, when no habits have been created within the app, trying to add a widget display an empty list, which is actually completely invisible. To the user, it looks like the app is just dimming the screen, instead of showing the habit selection dialog. When there are no habits, the app should say so, instead of showing an (invisible) empty list.

**Comment by alfred4x** [comment]
Hey @iSoron you were absolutely right . The issue i was facing occurs only when there is no habit created in the app. So when there is an habit in the app then when i try to drag the widget from the widget menu and release it on the home screen the name of that habit appears on the screen and after touching it the widget appears on the screen. So i think the issue is the widget can't be created unless theres at least one habit in the app. My suggestion is, in case when someone try to place widget without creating any habit in the app first, a prompt should appear telling the user to create an habit first instead of just dimming the screen. Thanks again.

**Comment by iSoron** [comment]
Fixed in e8e52db9b1b8
