### ISSUE TITLE
Re-add different midnight time (3am) for when the "next day" starts

### ISSUE THREAD

**Issue by slix** [iSoron/uhabits#607]
Starting the day at 3am was added in a75a27ad428e7cacb42ba12c2006b3b688f61b54 . But it seems to have disappeared during a re-write?

I'm a night owl and use the 1x1 habit widgets. I often am still completing habits after midnight, and that makes the habit widgets a headache to use (and somewhat demotivating).

Is https://github.com/iSoron/uhabits/blob/dev/android/uhabits-core/src/main/java/org/isoron/uhabits/core/utils/DateUtils.java#L170 the right place to change?

**Comment by iSoron** [comment]
I reverted those changes because it caused some strange issues with reminders and notifications. This was indeed how I implemented it before, but I no longer think modifying this function is the way to go, because this function is used in other places where the correct timestamp is required; for example, when scheduling reminders. We should probably create a new function for this delayed midnight and go over the source code to decide, in each case, which one should be called. Pull requests are very welcome for this.
