### ISSUE TITLE
Reset habits

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#61]
Reseting the progress of habits through multiple selection (like it's already implemented with colors) would be nice to have.

**Comment by iSoron** [comment]
By resetting the progress, do you mean deleting all the checkmarks? That would be a very destructive operation, and not used very often.

**Comment by sojusnik** [comment]
Exactly. Sometimes its more motivating to start over fresh, by deleting all checkmarks of a habit.

**Comment by iSoron** [comment]
I have decided not to implement this feature for the following reasons:
1. As I said, this is a very destructive operation. There is always a possibility that you may press it by mistake on the menu and end up confirming it. We already have one such operation (delete); let's not put even more.
2. There is not a lot of metadata about habits anyway, so "resetting" a habit can be easily accomplished by deleting it and then creating a new one with the same information.
3. It goes against the philosophy of the app. I understand that many other apps are focused on streaks, and that, after failing a streak, you might want to delete everything and start from scratch, since you have already lost all your progress anyway, but Loop is not like that. Every repetition in the past counts towards your score; it doesn't matter if it was one month, or even one year ago. Instead of restarting frequently, the app should encourage you to pick the habit up as soon as you can, and forget about a few missed days (or weeks).

**Comment by GutHib** [comment]
As this feature has been asked for again and again (and again and again) over the past nine years, I would like to comment on the reasons why it hasn't been implemented, because I think that the app has changed so much over the years that it may be time to reconsider.

#3 Concerning the philosophy of the app: As I pointed out in a different thread, to me the prime reason to do this is not failed streaks, but incomplete data. To my knowledge, back in the days the data you could enter was very basic, now you can track pretty much whatever you like and enter any data you want to. Tracking the meters you walked, the calories you ate or the words you wrote is an effort in itself, giving up on tracking isn't the same as giving up on a habit (obviously, you will consume calories whether you track them or not). If you want to track a bunch of very different things at the same time but circumstances kept you from entering data, starting from scratch can be the best (or even only) fix.

#2 If you track a number of things and have everything set up as widgets, creating it all from scratch can be quite an effort. And again, this is because the app has become so versatile.

#1 Whether or not it is destructive depends on how it is implemented. My preferred option would be to set this on a per habit basis, and possibly have a "start tracking" date rather than a downright delete button. This could hardly be used by mistake.

If you still don't want to add it, that's fine - just thought I'd point out that some of the arguments may not be as valid anymore as they used to be. Thanks and keep up the great work!
