### ISSUE TITLE
[feature] Color background for checkmark widgets that are ticked already 

### ISSUE THREAD

**Issue by AriApar** [iSoron/uhabits#615]
First of all, amazing work with this app, been using it for some time now and am amazed at how integral it has become for my phone usage.

I had a small UX suggestion on the checkmark widgets. A habit can either be explicitly checked by a user, implicitly checked if the user already fulfilled the number of times they needed to check the habit in the last X days, or unchecked. When a feature is explicitly checked, the widget background also changes color. I was wondering if it'd make sense for an implicitly checked widget to also have some color (perhaps with some transparency)

![Screenshot_20200803-212530__01](https://user-images.githubusercontent.com/4266136/89215518-779ed300-d5d1-11ea-9d3b-d05cd5ef15d3.jpg)

In the screenshot above, the ~blog post~ (edit: this should have said "friends&family", thanks for the correction @wobbba) widget would be the one I'm talking about, and it'd be nice to look at my screen and immediately distinguish between the colorful vs grey boxes, to see which habits I should do today and which are already done (checkmark already provides this but is less in-your-face)

Thanks for considering, and again, amazing work with your app!

**Comment by KristianTashkov** [comment]
To be honest I have the same consideration for the checkmarks in the app as well. On a dimmed screen you can't make the distinction(implicit check or unchecked) at a glance. It makes sense "color" to always mean success and playing with opacity to show the difference between explicit and implicit.

**Comment by wobbba** [comment]
> I was wondering if it'd make sense for an implicitly checked widget to also have some color (perhaps with some transparency)
Came here to suggest this, so +1, that would be great!!

> In the screenshot above, the blog post widget would be the one I'm talking about
I'm confused, the blog post one isn't implicitly checked, it's the "friends & family" one, that one should have some colour IMO.

I also think it would be cool if the transparency and/or saturation and/or brightness of the colour would change according to how far away you are from breaking the chain. 

E.g. if it's a once a week habit and you just did it yesterday the colour is at its brightest/most saturated/most opaque and slowly fades day by day until it's at its most dark/unsaturated/transparent on the last implicitly checked day and then one day later it goes to completely colourless with an X, the way it is now.

I would also love to see some heavy customization potential in the settings, e.g. min and max transparency/saturation/brightness, which of the three or multiple, maybe even functions of t he way it fades (linear, exponential, etc.), possibly even let the user input a custom function. Or customize how to handle short time windows: if it's a once per two days habit, should the colour be vibrant because it was completed yesterday or bleak because it's the last implicit day (I'd say the latter but why not let the user decide?) Similarly for 3 days and so on.

Anyway, the most important is that there's partial colour at all because as you said seeing it at a glance would be better and there is just something so satisfying about a wall of coloured habit-tiles :)
