### ISSUE TITLE
Change background message when hide completed is selected.

### ISSUE THREAD

**Issue by ghost** [iSoron/uhabits#622]
Hello.
When hide completed is selected and all habits are completed, the message shown is "You have no active habits."
Replacement with a tickmark and "you are done for today" would give me some well deserved dopamine.

**Comment by monilSoni** [comment]
I'm kind of new to open source and I'd like to try this out. Before making the code change I would like to discuss the change here. 

From what I understand, if the user has enabled the option to hide completed habits and has non completed habits for today, we would show this text. The check for completed habits can be found from the preferences. So that means we will have to put the checks for these to avoid the cases where user has archived the habits and the empty view is shown. 
Code change for the empty list would be here: https://github.com/iSoron/uhabits/blob/d997b1378d6874c59bd2bf6d73db89957edfa213/android/uhabits-android/src/main/java/org/isoron/uhabits/activities/habits/list/views/EmptyListView.kt#L44 I think. 

I've not deep dived into how to get the count of completed habits for today but I plan to look at it soon. Does this work?

**Comment by iSoron** [comment]
Closing this in favor of #700, which has a more detailed description of this task. Thanks again for the suggestion!
