### ISSUE TITLE
Open app without flashing

### ISSUE THREAD

**Issue by shuvashish76** [iSoron/uhabits#645]
It not a problem.We can say it's a minor improvement.
When we open the app it takes fraction of second to flash white background then it opens the app..

There are some apps like WPS office, Librera Pro, VLC etc who open their app without flashing, though they take little amount of time to open. These apps just wait that fraction second & open the app directly.

It would be nice if loop habit tracker also open without white flash.

(Sorry if his is related to android limitations)

**Comment by iSoron** [comment]
Thank you for the suggestion, @shuvashish76. As far as I am aware, we cannot delay showing the app until the content is loaded. We can optimize the code so that the loading happens faster, but there will always be some amount of flashing. For this reason, I'm closing this issue, but pull requests reducing this flashing are welcome.

**Comment by rsatenza** [comment]
Hey, is it possible to make the white flash a black flash in dark mode?

It is really unpleasant for the eyes and is inconsistent with a complete dark theme.

Thank you.
