### ISSUE TITLE
Global dark mode in Xiaomi MIUI causes visual glitches in Loop Habit Tracker

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#673]
## Problem

Some users have reported that some interface elements (such as the "+" icon to add new habits) have suddenly become very hard to see (see screenshot below). This seems to affect only Xiaomi phones using global dark mode. Since I don't own a Xiaomi phone, I unfortunately cannot investigate this issue further. Any additional details and pull requests to fix it are appreciated.

## Workaround

Disable MIUI global dark mode for Loop Habit Tracker.

## Screenshot
<img src="https://user-images.githubusercontent.com/4699657/100362705-6125e880-2fc1-11eb-826a-145c06efaffe.jpg" width=300 />

**Comment by AlbanSdl** [comment]
As you mentionned this bug comes from global dark theme introduced quite recently in MIUI.
The main issue here is that uHabits uses a custom implementation of dark theming that MIUI doesn't recognizes. That's why we can get another kind of dark theme (with app light theme combined with system dark theme - *and i prefer it as it keeps a color on the toolbar*)

<img src="https://user-images.githubusercontent.com/35579652/101355256-9cb09480-3896-11eb-9af2-92698cd1e78c.jpg" width="300px" height="624px" alt="screenshot"/>

I think the best option would be to update `com.google.android.material:material` and use the `Theme.MaterialComponents.DayNight` theme as explained [here](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#support-dark-theme) to prevent this kind of dark theme conflicts.

Tinting the icon with `app:iconTint` also works but i'm not sure it has the exact same color as the other buttons and it would be a bit hardcoded.
<img src="https://user-images.githubusercontent.com/35579652/101357637-01212300-389a-11eb-9ce8-29af8fed99f6.jpg" alt="screenshot" width="400px" height="175px"/>

And i also have this question: is there a reason to use pngs instead of vector drawables ?

**Comment by iSoron** [comment]
@AlbanSdl Thank you for the feedback. I have implemented your suggested fix in the branch `hotfix/1.8.11`. Here is also the [corresponding APK](https://github.com/iSoron/uhabits/files/5669824/loop-1.8.11-release.zip). Could you please try it out in your phone and confirm that the problem is fixed? I suggest backing up your data before updating to this APK, in case you want to downgrade back to version 1.8.10 later.

Prior to this fix, Loop didn't use `Theme.MaterialComponents.DayNight` because we originally implemented dark mode back in 2016, many years before Android officially supported it. Regarding vector drawables, yes, we should switch. Pull requests are very welcome.

**Comment by AlbanSdl** [comment]
DayNight themes have been created to use the same styles with different color values that's why we should change some xml of the app. I'll do it soon in a pull request (with vector drawables which will help merging both styles)
However when i was testing a first version of the merged themes i used a new line in `AppBaseTheme` in values-v29 that fixes our first problem:
```xml
<item name="android:forceDarkAllowed">false</item>
```
It prevents MIUI global dark mode from being used (and creating another dark theme). It solves the issue of the black add button

**Comment by iSoron** [comment]
I would like to solve this issue with the fewest changes as possible, so that it can be shipped as Loop 1.8.11. Pull requests switching to vector drawables are welcome, but I would only ship them in Loop 2.0.

If `forceDarkAllowed=false` solves the issue, I will go with that. Could you confirm that the current fix in `hotfix/1.8.11` also works? Thanks.

**Comment by AlbanSdl** [comment]
The current fix doesn't work as is (it needs more changes to styles to work well)
That's why forceDarkAllowed looks like a better solution... if the users are not using light theme with global dark theme (it has trouble displaying texts in settings and some popups)

**Comment by iSoron** [comment]
> The current fix doesn't work as is (it needs more changes to styles to work well)
> 
> That's why forceDarkAllowed looks like a better solution... if the users are not using light theme with global dark theme (it has trouble displaying texts in settings and some popups)

Could you please post a screenshot of this? Do the changes in `hotfix/1.8.11` fix the invisible add button?

**Comment by AlbanSdl** [comment]
If you want the fewest line changes, revert the last commit and use "forceDarkAllowed". This way the Material components will use the proper themes.

**Comment by iSoron** [comment]
> If you want the fewest line changes, revert the last commit and use "forceDarkAllowed". This way the Material components will use the proper themes and the problem will be solved

Could you please post a screenshot of the visual glitches you are experiencing with `hotfix/1.8.11`?

Do the changes in hotfix/1.8.11 fix the invisible add button?

**Comment by iSoron** [comment]
Loop 1.8.11 is [now available on GitHub Releases](https://github.com/iSoron/uhabits/releases/tag/1.8.11) and should become available soon on Google Play and F-Droid. If you have a Xiaomi phone and you were affected by this issue, please let us know if this release has solved the problem for you.

**Comment by iSoron** [comment]
Confirmed fixed in 1.8.11
