### ISSUE TITLE
Add a magnifying glass to search by habit name

### ISSUE THREAD

**Issue by KeronCyst** [iSoron/uhabits#676]
I have 40 habits set, so it can be difficult to find one that I'm looking for. Being able to run a search to quickly locate a habit in the overview would be super-helpful!

**Comment by ljl-covid** [comment]
I second this... I actually just came here to file a feature request about this, but looks like I've been preceded by six days.

The functionality may either filter through habits by name, search for a specific habit, or scroll to the habit searched for and highlight it; I don't know what would be better UX... I suspect filtering or scrolling+highlighting would work better for me personally, but ultimately, just like @KeronCyst, I have an unwieldy number of habits, and I've spent enough time staring at them that I could probably have written this feature request a thousand times in that time. Maybe it's not a typical use case, but hey, there's at least two of us!

**Comment by hiqua** [comment]
Why not I suppose, but I guess most users have something like 10 habits, and users with 40+ habits are outliers, so I don't think it will benefit many users.

Even for users with a lot of habits, what about better sorting / colors to quickly find the habit you need?

Another point: I'd have to time myself, but I'd guess finding a habit myself by scrolling would be faster than typing on a smartphone, and less error-prone obviously.

Actually I can say with confidence that with my ~30 habits, I wouldn't use a search function. Maybe with 60 habits it would start making sense (for me).

But if you want to open a PR I think it might be merged, since it should not conflict with other stuff.

**Comment by iSoron** [comment]
@KeronCyst @ljl-covid I'm not sure I understand the workflow here. After searching for the habit, what operation do you do next?  Do you (i) search for the habit, (ii) add a checkmark, (iii) search for another habit, (iv) add another checkmark? As @hiqua mentioned, I'm not sure a search function would actually save any time in this workflow, due to all the typing involved. Perhaps collapsible groups of habits (as suggested in #495) would work better.

**Comment by ljl-covid** [comment]
@iSoron yes, pretty much. I have many habits, admittedly likely many more than the average user (but do we actually know how the average user uses this apps? I don't even use it for things that you'd properly call "habits", for the most part), and I think that workflow would be fast for me.

I currently use color codes but that's not enough, and I keep staring anyway. Typing a couple of letters in a search filter would likely reduce the number of shown habits to just a couple, I don't feel like there would be *a lot* of typing involved.

Collapsible groups may work better for me than the current color coding, and I'd probably use those even with a search feature present, but I suspect I'd probably use the search feature the most.

I understand this may not reflect how others use the apps or the way you envision it, though. That's fine.

**Comment by KeronCyst** [comment]
@iSoron it's not usually to checkmark; I sometimes edit the frequency of a somewhat-new habit as I get in the groove of what I'm trying to do with it over weeks of experience with it (or I just messed up the initial frequency accidentally), and then I try to look through the list by frequency. So, sorting by frequency would be nice. I will try colors; I had forgotten about those. Collapsible groups sound like a great alternative, too!
