### ISSUE TITLE
Allow the user to sort habits by score

### ISSUE THREAD

**Issue by JouzaLoL** [iSoron/uhabits#73]
Display option to sort habits in the main screen by Current Streak, Last Streak, Star Rating etc.

**Comment by iSoron** [comment]
Hi Jouza, thank you for the suggestion. Just to make clear, it is already possible to sort the habits manually. If I understand correctly, your suggestion is to add an option to sort habits automatically by different criteria. The problem is that most of this information, with the exception of the star rating, is not currently displayed on the main screen. Maybe having a separate dashboard showing the top habits according to different statistics would be a better idea. This is somehow related to #51.

**Comment by iSoron** [comment]
This has been implemented in the `dev` branch. The app now allows you to sort by name, color and score.
