### ISSUE TITLE
DAY_OF_WEEK usage

### ISSUE THREAD

**Issue by sciamano** [iSoron/uhabits#74]
Hi, I was always wondering why in punch card etc, the week starts with SATURDAY (!). Sunday I could may be understand... After digging in the code, I am now worring about line 147 in `DateHelper.java`
`day.set(GregorianCalendar.DAY_OF_WEEK, 0);`
My problem is that according to java docs, the `Calendar.DAY_OF_WEEK` is taking values 1 to 7, not 0. You can check e.g. a code
```
GregorianCalendar day = new GregorianCalendar();
System.out.printf("day = %s, i = %d\n", "SUNDAY", day.SUNDAY);
System.out.printf("day = %s, i = %d\n", "MONDAY", day.MONDAY);
System.out.printf("day = %s, i = %d\n", "SATURDAY", day.SATURDAY);
```

Does it makes more sence to change the line to
`day.set(GregorianCalendar.DAY_OF_WEEK, day.getFirstDayOfWeek());`
can you comment?

...looks like related to #53

**Comment by iSoron** [comment]
Hi sciamano, nice to have someone looking over the source code. Throughout the code, it is assumed that the weekdays are numbered from 0 (Saturday) to 6 (Friday). A couple of places that make this assumption, for example, are [here][as1] and [here][as2]. The decision of assigning zero to Saturday was completely arbitrary, but having them start at zero is usually much more convenient. To keep things consistent, I would like to have every low-level function treat zero as Saturday. The views are then free to pick whatever day is better to start the week.

So, you are right that the line `day.set(GregorianCalendar.DAY_OF_WEEK, 0)` is wrong, since it relies on undocumented behaviour, but I would replace it instead with `day.set(GregorianCalendar.DAY_OF_WEEK, Calendar.SATURDAY)`.

To fix #53 it would be better to change [this method][as3] on HabitHistoryView. Instead of subtracting `todayWeekday` on the last line, we should subtract `todayWeekday + getFirstDayOfWeek` or something like that. We should probably also change [this method][as4]. Instead of starting at zero, `i` should start at `getFirstDayOfWeek`.

Please feel free to ask me any questions if something is still not clear.

[as1]: https://github.com/iSoron/uhabits/blob/dev/app/src/main/java/org/isoron/uhabits/models/RepetitionList.java#L128
[as2]: https://github.com/iSoron/uhabits/blob/dev/app/src/main/java/org/isoron/uhabits/helpers/DateHelper.java#L188-L215
[as3]: https://github.com/iSoron/uhabits/blob/dev/app/src/main/java/org/isoron/uhabits/views/HabitHistoryView.java#L112-L122
[as4]: https://github.com/iSoron/uhabits/blob/dev/app/src/main/java/org/isoron/uhabits/views/HabitHistoryView.java#L303-L311

**Comment by sciamano** [comment]
Hi Alinson, thanks for the explanations. That is always interesting how the others read a code. Before writing the issue I have marked few "candidates", but none of them overlap with methods you mentioned :)

**Comment by iSoron** [comment]
Discussion moved to #77
