### ISSUE TITLE
No response from notifications actions on lockscreen

### ISSUE THREAD

**Issue by vespa-r** [iSoron/uhabits#787]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
I want to snooze the notifications on the lock screen, but there is no response when I click it. It does not snooze and dismiss the notifications or direct me to unlock to complete the action.

## System information
 - Phone: Sony Xperia 5
 - Phone Operating System: Android 10
 - App version: 1.8.12

**Comment by hiqua** [comment]
Do you see the `Later` option? And nothing happens when you click it?

**Comment by iSoron** [comment]
I was able to reproduce this with Loop 1.8.12 on the emulator (Android 9.0 x86_64).

- In Loop 1.8.12, if the screen is **locked**, nothing happens when the user clicks "Later".
- In the dev branch, the situation is slightly better: clicking "Later" asks the user to unlock the screen, but after unlocking it, there is nothing there. After the screen is unlocked, the app should show a dialog to select the snooze interval instead.

**Comment by vespa-r** [comment]
> Do you see the `Later` option (if not, try to swipe the notification down first)? And nothing happens when you click it?

I can see the three options. `Yes` and `No` seem working but not `Later`. Just like @iSoron said nothing happens when click it.
