### ISSUE TITLE
Reminder rescheduling does not respect Dark theming choice

### ISSUE THREAD

**Issue by Mrnofish** [iSoron/uhabits#858]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
When rescheduling a reminder ("Later" option), the reschedule pop-up is themed with Light instead of Dark.

## Steps to reproduce
1. Enable **Dark Theme** from the drop down ... menu.
2. Set up a reminder
3. Wait for the reminder to trigger
4. Expand notification and pick **Later**
5. The pop-up and time selection control are both rendered with the Light theme

## System information
 - Phone: OP7P (guacamole)
 - Phone Operating System: Android 10 / Lineage 17.1
 - App version: 1.8.12

**Comment by hiqua** [comment]
I think the theme should be the system one for notifications and activities opened through notifications, but yes you're right it doesn't seem to follow the system theme.

We could probably get this for free if we switched to a proper datetime picker library.

**Comment by hiqua** [comment]
In SnoozeDelayPicker.kt, I think changing 
```kt
        val theme = R.style.Theme_AppCompat_Light_Dialog_Alert
```
to
```kt
        val theme = R.style.Theme_AppCompat_Dialog
```
is enough to get the "Select snooze delay" screen in the correct theme. The problem is that "Custom" will still open the datetime picker which is fully white. There's some theming logic commented out in the library which could help, but I guess it's been commented out for a reason.

We should probably just switch to https://developer.android.com/reference/com/google/android/material/timepicker/MaterialTimePicker

**Comment by iSoron** [comment]
@hiqua As mentioned in #865, that would be fine. PRs are welcome.
