### ISSUE TITLE
A month should not be treated as 30 days, and vice versa

### ISSUE THREAD

**Issue by Geeyun-JY3** [iSoron/uhabits#947]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
This is a logic bug.

It seems that Loop treat a month as 30 days, and vice versa.
1. Treat a month as 30 days: When setting the frequency as one time per month, it would be converted into every 30 days.
2. Treat 30 days as a month: see the second screenshot below.

## Steps to reproduce
This is a logic bug so no need steps.

## System information
 - Phone: Mi 8
 - Phone Operating System: Android 9
 - App version: 2.0.2

## Screenshots
A 1 time per month habit
![image](https://user-images.githubusercontent.com/49396421/120193804-67866d00-c24f-11eb-9d57-b43306a30cb5.png)
A 2 times per month habit
![image](https://user-images.githubusercontent.com/49396421/120194399-23479c80-c250-11eb-8868-940274ae8c04.jpg)
It covers March 1 and March 2. It does not make sense. It should only cover Feburary.

***
BTW, the bug  report issue template has a typo:
https://github.com/iSoron/uhabits/blob/bbf9da44e1fa7bccaff55645ea197cd37188e5f0/.github/ISSUE_TEMPLATE/bug_report.md#L18

It should be:
```
 - [ ] I have searched for similar issues, but did not find any matches. 
```

**Comment by iSoron** [comment]
Thank you for the bug report, @Geeyun-JY3. This has been fixed in the `hotfix/2.0.3` branch, and the fix should be available in the next version of the app. Here are some preview screenshots:

Every month:
![Screenshot_1622929875](https://user-images.githubusercontent.com/4699657/120906433-f8c65c80-c61e-11eb-8d38-6f968db05e09.png)

2 times per month:
![Screenshot_1622930015](https://user-images.githubusercontent.com/4699657/120906443-00860100-c61f-11eb-87a3-ed4b7f38a2bd.png)
