### ISSUE TITLE
More colors for habits

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#99]
(Translating some user feedback from Google Play Store)
...If there were more colors for habit, it'd be great!

**Comment by iSoron** [comment]
I guess we could add a few of the missing [Material Colors](http://www.materialui.co/colors), such as "orange" (we have "deep orange") and brown.

I am not allowing user-defined colors because I need to be able to tweak the colors according to the theme of the application. The colors in night mode, for example, must be much brighter and less saturated than the normal ones. Doing it dynamically doesn't look as good as picking the colors by hand.

**Comment by YPetremann** [comment]
The problem here is that with a lot of task, colors are redondant, for my part, I think we need 2 more grays, one between the two exinsting one and one lighter than the existing,
a brown, a pink, a indigo and a light blue,
